<?php
/**
 * Author: Hari Dornala <hari.dornala@nextbeemedia.com>
 * Date: 26-Mar-16
 * Time: 12:13 AM
 */

return array(
    '11th St',
    '1st St',
    '29th Ave',
    '2nd St',
    '3rd St',
    '4th St',
    '5th St',
    '6th St',
    '8th St',
    '9th St',
    'Adams St',
    'Adelphian Way',
    'Admiralty Ln',
    'Alameda Ave',
    'Alameda Ferry Terminal',
    'Alameda Nas (ngz)',
    'Alameda Rd',
    'Alaska Packer Pl',
    'Alta Vista',
    'Amber Isle',
    'Anchor Way',
    'Anderson Rd',
    'Annapolis Cir',
    'Ansel Ave',
    'Applegate Way',
    'Arbor St',
    'Argus Ct',
    'Arkansas',
    'Arlington Isle',
    'Armitage St',
    'Asby Bay',
    'Atlantic Ave',
    'Auburn Ct',
    'Auburn Dr',
    'Aughinbaugh Way',
    'Austin St',
    'Ave A',
    'Ave B',
    'Ave F',
    'Ave G',
    'Ave H',
    'Ave L',
    'Ave M',
    'Avenue E',
    'Avington Rd',
    'Avocet Ct',
    'Avondale Landing',
    'Azalea Dr',
    'Bainbridge Ct',
    'Bainbridge Square',
    'Balboa Ct',
    'Bali Ln',
    'Ballena Blvd',
    'Balleybay',
    'Bannister Ct',
    'Bannister Way',
    'Barbers Point Rd',
    'Barker Ct',
    'Barnegate Bay',
    'Barry Ct',
    'Bartlett Dr',
    'Basinside Way',
    'Bay Edge Rd',
    'Bay Farm Island Bicycle Bridge',
    'Bay Farm Island Bridge',
    'Bay Park Terrace',
    'Bay St',
    'Bayo Vista Ave',
    'Bayview Dr',
    'Baywalk Rd',
    'Baywood Rd',
    'Beach Rd',
    'Beaufort Harbor Landing',
    'Begonia Dr',
    'Belmont Pl',
    'Belmont Way',
    'Benedict Ct',
    'Benton St',
    'Berkshire Rd',
    'Bertero Ct',
    'Bertero Square',
    'Bird Ct',
    'Biscay Bay',
    'Bishop St',
    'Bismarck Ln',
    'Blanding Ave',
    'Bordwell Ct',
    'Bosshard Ct',
    'Bowman Ct',
    'Brehaut Ct',
    'Bridgeview Isle',
    'Briggs Ave',
    'Brighton Ct',
    'Brighton Rd',
    'Brithorn Ln',
    'Britt Ct',
    'Brittany Dr',
    'Broadway',
    'Broadway',
    'Brower Ct',
    'Brown St',
    'Brunswick Rd',
    'Brush St',
    'Bruzzone Dr',
    'Bryant Ave',
    'Buena Vista Ave',
    'Burbank St',
    'Burgner Ave',
    'Calhoun St',
    'California',
    'Callan Pl',
    'Cam Del Valle',
    'Camanoe Ln',
    'Cambridge Dr',
    'Camden Rd',
    'Camellia Dr',
    'Campbell Blvd',
    'Campbell Dr',
    'Cape Cod Ct',
    'Capella Ln',
    'Capetown Dr',
    'Captains Dr',
    'Cardigan Bay',
    'Carl Vinson',
    'Carob Ln',
    'Caroline St',
    'Castlebar Pl',
    'Catalina Ave',
    'Cedar St',
    'Centennial Ave',
    'Central Ave',
    'Centre Ct',
    'Cerro Vista',
    'Cerruti Ct',
    'Challen Ct',
    'Challenger Dr',
    'Channing Way',
    'Chapin St',
    'Chatham Pointe',
    'Cheshire Ct',
    'Chester St',
    'Chestnut St',
    'Cheswick Ct',
    'Chicago',
    'Chilmark Ln',
    'Chinaberry Ln',
    'Chipman St',
    'Christensen Ct',
    'Cimarron St',
    'Clarke Ln',
    'Clay St',
    'Clement Ave',
    'Cleveland Ct',
    'Clinton Ave',
    'Clipper Dr',
    'Clubhouse Memorial Rd',
    'Cohen Ct',
    'Cola Ballena',
    'Cole Ln',
    'Coleport Landing',
    'College Ave',
    'Concordia St',
    'Constance Cir',
    'Constitution Way',
    'Cook Ln',
    'Coral Reef Pl',
    'Coral Reef Rd',
    'Coral Sea St',
    'Cork Rd',
    'Cormorant Ln',
    'Cornelius Square',
    'Cornell Dr',
    'Corpus Christi Rd',
    'Costanoan Ct',
    'Cotati Ln',
    'Cotella Ct',
    'Cottage St',
    'Country Isle',
    'County Rd',
    'Courageous Ct',
    'Court St',
    'Court Street Methodist Episcopal Church',
    'Cove Rd',
    'Crane Ct',
    'Creedon Cir',
    'Crist St',
    'Crolls Garden Ct',
    'Crown Dr',
    'Cumberland Ct',
    'Cumberland Way',
    'Curlew Ct',
    'Cypress St',
    'Dahlia Dr',
    'Damon Ct',
    'Danbrook Ct',
    'Dayton Ave',
    'Decatur Ln',
    'Decelle Ct',
    'Del Mar Ave',
    'Denke Dr',
    'Depassier Way',
    'Diapian Bay',
    'Digiorgio Ln',
    'Dolphin Ct',
    'Doolittle Dr',
    'Doris Ct',
    'Dow Ct',
    'Dowitcher Ct',
    'Dowling Ln',
    'Dresden Bay',
    'Driftwood Ln',
    'Drum',
    'Duarte Ct',
    'Dublin Way',
    'Dufour Ln',
    'Dunlin Ln',
    'Dutchcap Ln',
    'Dwinelle Ct',
    'E Campus Dr College Of Alameda',
    'Eagle Ave',
    'Eagle Rd',
    'Easter Ln',
    'Eastshore Dr',
    'Eclipse Ct',
    'Edison Ct',
    'Egret Ct',
    'El Capitan Ct',
    'El Paseo',
    'El Portal',
    'El Sereno',
    'Ellen Crag Ave',
    'Ellis Ct',
    'Elm St',
    'Emeric Ln',
    'Emerson Terrace',
    'Encinal Ave',
    'Encounter Bay',
    'Ennis Pl',
    'Ennismore Ct',
    'Entrance Rd',
    'Esterbrook Ct',
    'Eugenia Ct',
    'Evans Ct',
    'Evelyn Ct',
    'Everett St',
    'Fair Haven Rd',
    'Fair Oaks Ave',
    'Fairview Ave',
    'Fairway Pl',
    'Fallon Ln',
    'Ferro Ct',
    'Ferry Point',
    'Fiji Ln',
    'Fillmore St',
    'Fir Ave',
    'Fir Pl',
    'Fitch Ct',
    'Fitchburg Ave',
    'Fletcher Ct',
    'Flint',
    'Flora Vista',
    'Flower Ln',
    'Foley St',
    'Fontana Dr',
    'Fortmann Way',
    'Fortress Isle',
    'Foster St',
    'Fountain St',
    'Franciscan Way',
    'Fremont Dr',
    'Fruitvale Ave',
    'Fulton Ln',
    'Fundy Bay',
    'Gainsborough Ct',
    'Galway Bay',
    'Garden Rd',
    'Garden Way',
    'Gardenia Terrace',
    'Garfield Ave',
    'Gibbons Dr',
    'Gilbert Ln',
    'Gilman Ln',
    'Ginger Ln',
    'Glenview St',
    'Glenwood Isle',
    'Gompers',
    'Gonsalves Ct',
    'Gould Ct',
    'Grace Ct',
    'Grand St',
    'Greenbrier Rd',
    'Greenwald Ln',
    'Gresham Dr',
    'Grove St',
    'Haight Ave',
    'Haile St',
    'Hamilton Ln',
    'Hampton Ct',
    'Hancock St',
    'Hansen Ave',
    'Harbor Bay Pkwy',
    'Harbor Bay Pkwy',
    'Harbor Light Rd',
    'Harbor Rd',
    'Harvard Dr',
    'Hatfield Ln',
    'Hawthorne St',
    'Hays Ct',
    'Hazel Ln',
    'Hecker Ct',
    'Hercules Ct',
    'Heron Ct',
    'Hibbard St',
    'High St',
    'Hillery Way',
    'Hollister Ave',
    'Holly Oak Ln',
    'Holly St',
    'Holtz Ct',
    'Hoover Ct',
    'Hudson Bay',
    'Hudson Dr',
    'Hwy 260',
    'Hwy 61',
    'Independence Dr',
    'Indian Bay',
    'Inverness Ct',
    'Inverness Way',
    'Invincible Ct',
    'Ironwood Rd',
    'Island Dr',
    'Jack London Ave',
    'Jack London Ave',
    'Jackson St',
    'Janis Cir',
    'Jay St',
    'Jervis Bay',
    'Johnson Ave',
    'Jost Ln',
    'Jouett Square',
    'Justin Cir',
    'Kansas City',
    'Kara Rd',
    'Keil Bay',
    'Kevington Pl',
    'Kilkenny Ct',
    'Kilkenny Pl',
    'Killarney Pl',
    'Killdeer Ct',
    'Killybegs Rd',
    'Kings Rd',
    'Kingfisher Ave',
    'Kingsbury Ct',
    'Kingston Ln',
    'Kinkaid Ct',
    'Kinkaid Square',
    'Kirk',
    'Kiska',
    'Kitty Hawk Pl',
    'Kitty Hawk Rd',
    'Kofman Ct',
    'Kofman Pkwy',
    'Kollmann Cir',
    'La Campania',
    'La Cresta',
    'La Jolla Dr',
    'Lafayette St',
    'Lagorio Ct',
    'Laguna Vista',
    'Lagunaria Ln',
    'Lakehurst Cir',
    'Larchmont Isle',
    'Laurel St',
    'Lavagetto Ct',
    'Lawrence Rd',
    'Lea Ct',
    'Leeward Ln',
    'Lemoore Rd',
    'Leonard Ct',
    'Lewelling Ct',
    'Lexington St',
    'Liberty Ave',
    'Lilac St',
    'Limerick Ln',
    'Lina Ave',
    'Lincoln Ave',
    'Lincoln Ln',
    'Linda Vista',
    'Linden St',
    'Madison St',
    'Magnolia Dr',
    'Main St',
    'Maitland Dr',
    'Mallard Ln',
    'Mangrove Ln',
    'Maple Way',
    'Marcuse St',
    'Marianas Ln',
    'Marina Dr',
    'Marina Village Pkwy',
    'Marina Village Pkwy:marina Square Dr (north Jctn)',
    'Mariner Square Dr',
    'Mariner Square Loop',
    'Marion Ct',
    'Market St',
    'Mars',
    'Marshall Way',
    'Marshall Way',
    'Marti Rae Ct',
    'Mastick Ct',
    'Matson Ln',
    'Mayport Cir',
    'Mcdonnel Rd',
    'Mckay Ave',
    'Mcmurty Ct',
    'Mcsherry Ln',
    'Mcsherry Way',
    'Mecartney Rd',
    'Melrose Ave',
    'Memphis Ln',
    'Meyers Ave',
    'Millington Ct',
    'Mingo Ln',
    'Minturn St',
    'Miranda Ct',
    'Mitchell Ave',
    'Monarch St',
    'Monte Vista Ave',
    'Montego Bay',
    'Monterey Cir',
    'Moonlight Terrace',
    'Moore Ct',
    'Moreland Dr',
    'Morton St',
    'Mosley Ave',
    'Moss Pointe',
    'Mound St',
    'Mozart St',
    'Mt Hood',
    'Mulberry St',
    'Mulvany Cir',
    'N Loop Rd',
    'N Star Rd',
    'Nakayama Ct',
    'Nantucket Way',
    'Nason St',
    'Nautilus St',
    'Navy Way',
    'Neptune Gardens Ave',
    'Nevada Dr',
    'Newport Rd',
    'Nimitz Dr',
    'Noble Ave',
    'Norfolk Ave',
    'Norfolk Rd',
    'Norman Ln',
    'Northwood Dr',
    'Norwich Rd',
    'Nottingham Ct',
    'Nottingham Dr',
    'Oak Park Dr',
    'Oak St',
    'Oceana St',
    'Ohio',
    'Ohlone St',
    'Oldcastle Ln',
    'Oleander Ave',
    'Orion St',
    'Orr Ct',
    'Orr Rd',
    'Otis Dr',
    'Oyster Pond Rd',
    'Oyster Shoals',
    'Pacific Ave',
    'Pacific Marina',
    'Packet Landing Rd',
    'Packet Landing Rd',
    'Page St',
    'Palace Ct',
    'Palm Beach Ln',
    'Palmera Ct',
    'Pan Am Way',
    'Panoramic Dr',
    'Parfait Ln',
    'Parish Ct',
    'Park Ave',
    'Park Ave E',
    'Park Ave W',
    'Park St',
    'Park St',
    'Parket Landing',
    'Parodi Ct',
    'Paru St',
    'Pattiani Way',
    'Payot Ct',
    'Payot Ln',
    'Peach St',
    'Pearl Harbor Rd',
    'Pearl St',
    'Pease Ct',
    'Pelican Ct',
    'Pensacola Ln',
    'Pensacola Rd',
    'Percy Ln',
    'Phoenix Ln',
    'Pickrell Square',
    'Pioneer Ct',
    'Plover Ct',
    'Poggi St',
    'Pomeroy Ln',
    'Pond Isle',
    'Porta Ballena',
    'Portola Ave',
    'Posey Tube',
    'Post Office Ct',
    'Post St',
    'Powell St',
    'Powers Ct',
    'Puddingstone Rd',
    'Purcell Dr',
    'Pyne Ln',
    'Pyro',
    'Queens Rd',
    'Railroad Ln',
    'Rainbow Ct',
    'Ralph Appezzato Memorial Pkwy',
    'Ranger Ct',
    'Ratto Rd',
    'Ravens Cove Ln',
    'Red Jacket Ln',
    'Redhook Ln',
    'Redondo Ct',
    'Regent St',
    'Regulus Ct',
    'Remmel Ct',
    'Riddell Ln',
    'Road A',
    'Road B',
    'Roanoke Dr',
    'Robert Davey Jr',
    'Robert Davey Jr Dr:channing Way',
    'Robert Louis Stevenson Ave',
    'Rock',
    'Rock Isle',
    'Ron Cowan Pkwy',
    'Roosevelt Dr',
    'Rosefield Loop',
    'Rosewood Way',
    'Ross Rd',
    'Roth Ln',
    'Rowe Ct',
    'Roxburg Ln',
    'Rte 260',
    'Rutland Ct',
    'S Loop Rd',
    'S Shore Center',
    'Sable Pointe',
    'Sacramento',
    'Sage Ln',
    'Salmon Rd',
    'San Antonio Ave',
    'San Antonio Ave',
    'San Diego Rd',
    'San Diego Rd',
    'San Jose Ave',
    'San Pedro Rd',
    'Sand Beach Pl',
    'Sand Beach Rd',
    'Sand Harbor',
    'Sand Harbor Rd',
    'Sand Hook Isle',
    'Sandalwood Isle',
    'Sandcreek Way',
    'Sanderling Ct',
    'Sandpiper Ct',
    'Sandpiper Pl',
    'Santa Clara Ave',
    'Santa Clara Ave',
    'Santa Cruz Ln',
    'Santa Rosa Ln',
    'Saratoga St',
    'Sath Ct',
    'Savana Ln',
    'Schiller St',
    'Schroeder Ln',
    'Sea Bridge',
    'Sea Bridge Ct',
    'Sea Bridge Way',
    'Sea Horse',
    'Sea View Pkwy',
    'Seaborn Ct',
    'Seagull Ln',
    'Seattle Rd',
    'Seeback Ln',
    'Seminary Ave',
    'Serenade Pl',
    'Shamrock Ln',
    'Shaner Dr',
    'Shannon Cir',
    'Sharon Rd',
    'Shasta',
    'Shasta',
    'Sheffield Rd',
    'Sheffield Way',
    'Shell Gate Pl',
    'Shell Gate Rd',
    'Shepardson Ln',
    'Sherman St',
    'Sherwood Ln',
    'Shoreline Dr',
    'Shoreline Dr',
    'Shorepoint Ct',
    'Siegfried Ln',
    'Silva Ln',
    'Singleton Ave',
    'Skyhawk St',
    'Smith Ct',
    'Solomon Ln',
    'South Shore Center W',
    'Southwood Dr',
    'Souza Ct',
    'Spalding Square',
    'Spencer Rd',
    'Spruce St',
    'St Charles St',
    'St Margaret Ct',
    'Stanbridge Ct',
    'Stanbridge Ln',
    'Stanford St',
    'Stanton St',
    'Stardust Pl',
    'State Highway 61',
    'State Route 260',
    'Sterling Ave',
    'Steuben Bay',
    'Steuben Bay',
    'Stewart Ct',
    'Stone Harbor',
    'Stonington Pointe',
    'Straub Way',
    'Sunny Cove Cir',
    'Sunrise Ct',
    'Sunset Rd',
    'Sweeney Ln',
    'Sweet Rd',
    'Sweet Way',
    'Swift Ct',
    'Tahiti Ln',
    'Tarryton Isle',
    'Taylor Ave',
    'Teal Ln',
    'Tern Ln',
    'Texas',
    'Thatch Ln',
    'Thau Way',
    'Thompson Ave',
    'Thurles Pl',
    'Tideway Dr',
    'Tilden Way',
    'Times Way',
    'Tipperary Ct',
    'Tipperary Ln',
    'Tobago Ln',
    'Todd St',
    'Tonga Ln',
    'Toyon Terrace',
    'Tralee Ln',
    'Tregloan Ct',
    'Trellis Ln',
    'Tripoli',
    'Triumph Dr',
    'Tucker Ave',
    'Tullamore Pl',
    'Tuttle Ln',
    'Tynan Ave',
    'Tynebourne Pl',
    'Ulster Pl',
    'Union St',
    'Van Buren St',
    'Verdemar Dr',
    'Verdi St',
    'Vernalis Ln',
    'Versailles Ave',
    'Veterans Ct',
    'Via Alamosa',
    'Via Aliso',
    'Via Bahia',
    'Via Bonita',
    'Via Corta',
    'Victoria Bay',
    'Viking St',
    'Vista Rd',
    'Volberg Ct',
    'W Atlantic Ave',
    'W Campus Dr',
    'W Capt Dodge Pl',
    'W Essex Dr',
    'W Hornet Ave',
    'W Mall Square',
    'W Midway Ave',
    'W Oriskany Ave',
    'W Pacific Ave',
    'W Ranger Ave',
    'W Red Line Ave',
    'W Seaplane Lagoon',
    'W Ticonderoga Ave',
    'W Tower Ave',
    'W Trident Ave',
    'Wake Ln',
    'Walnut St',
    'Washington Ct',
    'Washington St',
    'Washington Way',
    'Washoe Ct',
    'Water Works Ln',
    'Waterfall Isle',
    'Waterford Pl',
    'Waterton St',
    'Waterview Isle',
    'Wayne Ct',
    'Webb Ave',
    'Weber St',
    'Webster St',
    'Webster Street Tube',
    'Weiss Ct',
    'Wellfleet Bay',
    'Westline Dr',
    'Wexford Pl',
    'Weymouth Ct',
    'Whimbrel Ct',
    'Whitehall Pl',
    'Whitehall Rd',
    'Wichita',
    'Willet Ct',
    'Willie Stargell Ave',
    'Willis Ln',
    'Willow St',
    'Winant Way',
    'Wind River Way',
    'Windemere Isle',
    'Windsor Dr',
    'Windward Ln',
    'Wood St',
    'Wright Ln',
    'Yale Dr',
    'Yorkshire Pl',
    'Yorkshire Rd',
    'Yosemite Ave',
    'Young St'
);