<?php
return array(
    'Acorn Way',
    'Adam Way',
    'Alejandra Ave',
    'Almendral Ave',
    'Altree Ct',
    'Arthur Ln',
    'Ashfield Rd',
    'Atherton Ave',
    'Austin Ave',
    'Barmetta Way',
    'Barry Ln',
    'Bassett Ln',
    'Belbrook Way',
    'Belleau Ave',
    'Bergesen Ct',
    'Brittany Meadows',
    'Britton Ave',
    'Broadacres Rd',
    'Burns Ave',
    'Callado Way',
    'Cam Al Lago',
    'Cam De Los Arboles',
    'Cam Por Los Arboles',
    'Capper Ct',
    'Carolina Ln',
    'Catalpa Dr',
    'Cebalo Ln',
    'Clay Dr',
    'Coghlan Ln',
    'Country Ln',
    'Cowell Ln',
    'De Bell Dr',
    'Deodora Dr',
    'Dinkelspiel Station Ln',
    'Douglass Way',
    'Edge Rd',
    'Edwards Ln',
    'Elena Ave',
    'Elizabeth Way',
    'Elm Pl',
    'Emilie Ave',
    'Encino Rd',
    'Fair Oaks Ln',
    'Faxon Forest',
    'Faxon Rd',
    'Fennwood Dr',
    'Fletcher Dr',
    'Fleur Pl',
    'Flood Cir',
    'Frederick Ave',
    'Fredrick Ave',
    'Greenoaks Dr',
    'Gresham Ln',
    'Heather Dr',
    'Hilary Ln',
    'Holbrook Ln',
    'Howard Way',
    'Inglewood Ln',
    'Irving Ave',
    'Isabella Ave',
    'James Ave',
    'Jennings Ln',
    'Juniper Dr',
    'Karen Way',
    'Kilroy Way',
    'Knoll Vista',
    'Laburnum Rd',
    'Lane Pl',
    'Larch Dr',
    'Leon Way',
    'Lilac Dr',
    'Linda Vista Ave',
    'Lloyden Dr',
    'Lloyden Park Ln',
    'Logan Ln',
    'Lowery Dr',
    'Lupin Ln',
    'Macbain Ave',
    'Madrone Rd',
    'Mandarin Way',
    'Manzanita Rd',
    'Maple Leaf Way',
    'Marianna Ln',
    'Marymont Ave',
    'Mccormick Ln',
    'Melanie Ln',
    'Mercedes Ln',
    'Mesa Ct',
    'Michaels Way',
    'Middlegate St',
    'Monte Vista Ave',
    'Moulton Dr',
    'Mt Vernon Ln',
    'Mulberry Ln',
    'N Gate',
    'Nora Way',
    'Normandy Ln',
    'Northgate St',
    'Odell Pl',
    'Orchard Hills St',
    'Park Dr',
    'Parker Ave',
    'Patricia Dr',
    'Polhemus Ave',
    'Prado Secoya St',
    'Prior Ln',
    'Rebecca Ln',
    'Ridge View Dr',
    'Rittenhouse Ave',
    'Robleda Dr',
    'Sargent Ln',
    'Selby Ln',
    'Serrano Dr',
    'Shearer Dr',
    'Snowden Ave',
    'Spencer Ln',
    'Spencer Ln',
    'Stevenson Ln',
    'Stevick Dr',
    'Surrey Ln',
    'Sutherland Dr',
    'Tallwood Ct',
    'Toyon Rd',
    'Tuscaloosa Ave',
    'Valley Ct',
    'Victoria Dr',
    'Victoria Way',
    'Virginia Ln',
    'Walsh Rd',
    'Watkins Ave',
    'Wilburn Ave',
    'Wisteria Way'
);