<?php
/**
 * Author: Hari Dornala <hari.dornala@nextbeemedia.com>
 * Date: 02-Apr-16
 * Time: 1:09 AM
 */

return array(
    'Academy Ave',
    'Academy Ct',
    'Adelaide Way',
    'Alden Ct',
    'Alden St',
    'Alhambra Dr',
    'All View Way',
    'Alomar Way',
    'Altura Way',
    'Anita Ave',
    'Anita Ct',
    'Antique Forest Ln',
    'Arbor Ave',
    'Arden Ln',
    'Arroyo View Cir',
    'Arthur Ave',
    'Avon St',
    'Barclay Way',
    'Bartlett Way',
    'Bay Ct',
    'Belburn Dr',
    'Belle Monti Ave',
    'Belmont Canyon Rd',
    'Belmont Woods Way',
    'Benson Way',
    'Biddulph Way',
    'Bishop Rd',
    'Briarfield Way',
    'Briarwood Way',
    'Bridge Ct',
    'Bryce Ct',
    'Cambridge St',
    'Camino Vista Ct',
    'Carlmont Dr',
    'Casa Bona Ave',
    'Chesterton Ave',
    'Chevy St',
    'Christian Ct',
    'Christian Dr',
    'Chula Vista Dr',
    'Cipriani Blvd',
    'Civic Ln',
    'Clee St',
    'Cliffside Ct',
    'Clipper Ct',
    'Clipper Dr',
    'Cobblestone Ln',
    'College View Way',
    'Comstock Cir',
    'Concourse Dr',
    'Concourse Pl',
    'Continentals Way',
    'Cornish Way',
    'Coronet Blvd',
    'Courtland Rd',
    'Covington Rd',
    'Crest View Ave',
    'Dairy Ln',
    'Dale View Ave',
    'Davey Glen Rd',
    'Davis Dr',
    'Dekoven Ave',
    'Desvio Way',
    'Dionne Ct',
    'E St',
    'Edgewood Pl',
    'El Verano Way',
    'Elder Dr',
    'Elmer St',
    'Emmett Ave',
    'Encline Way',
    'English Ct',
    'Escondido Way',
    'Ewell Rd',
    'Fairway Dr',
    'Farallon Dr',
    'Fernwood Way',
    'Flasner Ln',
    'Folger Ct',
    'Folger Dr',
    'Forest Ave',
    'Francis Ave',
    'Francis Ct',
    'Furlong St',
    'Garden Ct',
    'Geraldine Way',
    'Gordon Ave',
    'Granada St',
    'Hainline Dr',
    'Hallmark Dr',
    'Hastings Dr',
    'Haydon Ct',
    'Heritage Ct',
    'Highgate Ave',
    'Highland Ct',
    'Highlands Ct',
    'Hill St',
    'Hiller St',
    'Hillman Ave',
    'Holly Rd',
    'Irene Ct',
    'Irwin St',
    'Island Pkwy',
    'Judson St',
    'Julia Ct',
    'Kedith St',
    'Kimmie Ct',
    'Kingston Rd',
    'Kittie Ln',
    'Korbel Way',
    'Ladera Way',
    'Lake Rd',
    'Lake Road Trail',
    'Lane St',
    'Lassen Dr',
    'Leigh Way',
    'Lincoln Ave',
    'Lodge Dr',
    'Loma Vista Ln',
    'London Ln',
    'Longfellow Dr',
    'Lori Ct',
    'Lori Dr',
    'Lower Lock Ave',
    'Lyall Way',
    'Lyndhurst Ct',
    'Lyon Ave',
    'Malcolm Ave',
    'Manchester Ln',
    'Manzanita Ave',
    'Marburger Ave',
    'Marine View St',
    'Marsten Ave',
    'Masonic Way',
    'Maywood Dr',
    'Meadow Park Cir',
    'Merry Moppet Ln',
    'Mezes Ave',
    'Middle Rd',
    'Middlesex Rd',
    'Miller Ave',
    'Mills Ave',
    'Miramar Terrace',
    'Misty Ln',
    'Molitor Rd',
    'Monserat Ave',
    'Monte Cresta Ct',
    'Monte Cresta Dr',
    'Mountain View Ave',
    'Muir Way',
    'Mulberry Ct',
    'N Rd',
    'Naughton Ave',
    'Newcastle Ln',
    'North Ct',
    'Northampton Ln',
    'Oak Ct',
    'Oak Tree Ln',
    'Oneill Ave',
    'Oxford Ct',
    'Oxford Way',
    'Paddington Ct',
    'Palmer Ave',
    'Parkridge Ct',
    'Phyllis Ct',
    'Pine Knoll Dr',
    'Plateau Dr',
    'Ponce Ave',
    'Prindle Rd',
    'Pullman Ave',
    'Ralston Ranch Rd',
    'Read Ave',
    'Reposo Way',
    'Ridge Rd',
    'Ridgewood Ct',
    'Rinconada Cir',
    'Robert Ave',
    'Robin Whipple Way',
    'Rose Ln',
    'Ross St',
    'Roxbury Way',
    'Ruth Ave',
    'Ruth Rd',
    'S Rd',
    'San Ardo Way',
    'San Juan Blvd',
    'Seagate Dr',
    'Seagate Pl',
    'Seagate Way',
    'Sem Ln',
    'Semeria Ave',
    'Sequoia Way',
    'Sherborne Dr',
    'Shirley Rd',
    'Skymont Ct',
    'Skymont Dr',
    'Soho Cir',
    'Solana Ct',
    'Solana Dr',
    'Somerset Ct',
    'Somerset Dr',
    'Sotocastle Ln',
    'Southview Ct',
    'Spring Ln',
    'St James Rd',
    'Sterling View St',
    'Sunnyslope Ave',
    'Sussex Ct',
    'Tahoe Dr',
    'Talbryn Dr',
    'Talbryn Ln',
    'Terrace Dr',
    'Thurm Ave',
    'Tioga Way',
    'Treasure Island Dr',
    'Upper Lock Ave',
    'Valdez Ave',
    'Valerga Dr',
    'Valley View Ave',
    'Vannier Dr',
    'Villa Ave',
    'Village Ct',
    'Village Dr',
    'W Naughton Ave',
    'Wakefield Ct',
    'Wakefield Dr',
    'Waltermire St',
    'Waltham Cross St',
    'Waterloo Ct',
    'Wemberly Dr',
    'Whiteridge Rd',
    'Williams Ave',
    'Willow Ln',
    'Winding Way',
    'Witheridge Rd',
    'Yorkshire Way',
    'Yosemite Dr'
);