<?php
/**
 * Author: Hari Dornala <hari.dornala@nextbeemedia.com>
 * Date: 09-Apr-16
 * Time: 1:17 AM
 */

return array(
    '1st St',
    'Abbey Ct',
    'Adams St',
    'Addison Ct',
    'Alder Ct',
    'Allen Way',
    'Alta Loma',
    'Anderson Ln',
    'Andrew Ct',
    'Anita Cir',
    'Arbor Ct',
    'Ardmore Ct',
    'Ardmore Way',
    'Arguello Dr',
    'Aspinwall Dr',
    'Atkins Ct',
    'Audrey Ct',
    'Baker Ct',
    'Baker St',
    'Banbury Ct',
    'Banbury Way',
    'Bantry Way',
    'Barton Way',
    'Bay Vista Ct',
    'Baylor Ct',
    'Bayshore Rd',
    'Bayview Cir',
    'Belvedere Dr',
    'Benicia-martinez Bridge',
    'Bigler Ct',
    'Birch Rd',
    'Blake Ct',
    'Blanchard Ln',
    'Bolton Cir',
    'Bonita Bahia',
    'Bradford Ct',
    'Bradford Way',
    'Braemer Ct',
    'Brandon Pl',
    'Breck Ct',
    'Brentwood Dr',
    'Bridgeview Ct',
    'Brown Ct',
    'Buchanan St',
    'Buckeye Ct',
    'Buena Tierra St',
    'Buena Vista',
    'Byron Ct',
    'California Ct',
    'Cambridge Dr',
    'Camel Rd',
    'Camellia Ct',
    'Campas Ct',
    'Canyon Ct',
    'Capitol Dr',
    'Carlisle Ct',
    'Carlisle Pl',
    'Carlisle Way',
    'Carolina Dr',
    'Carquinez Ct',
    'Carsten Cir',
    'Casa Grande Pl',
    'Casa Grande St',
    'Casey Ct',
    'Chadwick Ct',
    'Chadwick Way',
    'Channing Cir',
    'Charles Ct',
    'Charmian Ct',
    'Chelsea Hills Dr',
    'Cheryl Dr',
    'Church St',
    'Claverie Way',
    'Clearview Cir',
    'Clifton Ct',
    'Clos Duvall Ct',
    'Clyne Ct',
    'Columbia Cir',
    'Community Park Dr',
    'Cooper Dr',
    'Corcoran Ct',
    'Corrigan Ct',
    'Corte Del Sol',
    'Corte Dorado',
    'Cove Way',
    'Currey Ct',
    'Cypress Ct',
    'Daffodil Dr',
    'Dale Ct',
    'Dalton Ct',
    'Daniel Hills Ct',
    'Dartmouth Pl',
    'De Benedetti Ct',
    'Del Centro',
    'Denfield Ave',
    'Dillon Point Rd',
    'Dominic Ct',
    'Dorset Way',
    'Dover Cir',
    'Drolette Way',
    'Dundee Way',
    'Durham Ct',
    'Duvall Ct',
    'E 2nd St',
    'E 3rd St',
    'E 4th St',
    'E 5th St',
    'E 6th St',
    'E 7th St',
    'E B St',
    'E Channel Rd',
    'E F St',
    'E G St',
    'E I St',
    'E J St',
    'E K St',
    'E L St',
    'E N St',
    'E O St',
    'E S St',
    'E Seaview Dr',
    'E T St',
    'E Tennys Dr',
    'Earl Ct',
    'East E Street',
    'Eaton Ct',
    'Edna Ct',
    'Egret Ct',
    'El Bonito Way',
    'El Paseo',
    'Elane Way',
    'Ellie Ct',
    'Essex Ct',
    'Essex Way',
    'Francisca Ct',
    'Fry Ct',
    'Fuchsia Dr',
    'Gallagher Dr',
    'Gardenia Ct',
    'George Ct',
    'Gerald Ct',
    'Getty Ct',
    'Gigey Dr',
    'Gill Ct',
    'Gill Way',
    'Gloria Way',
    'Goettel Ct',
    'Golden Slopes Ct',
    'Goldenhill Way',
    'Goodyear Rd',
    'Gordon Ct',
    'Grant Ct',
    'Gray Ct',
    'Greenbrier Ct',
    'Grove Cir',
    'Gull Point',
    'Hall Ct',
    'Hanlon Way',
    'Harbor Rd',
    'Harbor Vista Ct',
    'Hastings Dr',
    'Havenhill Dr',
    'Hawthorne Ln',
    'Heather Ct',
    'Helane Ct',
    'Hillcrest Ave',
    'Hospital Rd',
    'Hubbs Ct',
    'Hugh Ct',
    'Incline Pl',
    'Industrial Ct',
    'Industrial Way',
    'Iowa St',
    'James Ct',
    'Janet Ct',
    'Jasmine Ct',
    'Jasper Ct',
    'Johns Pl',
    'Karen Dr',
    'Kearney St',
    'Kellyn Ct',
    'Kerry Ct',
    'Kip Ct',
    'Knight Dr',
    'Kuhland Alley',
    'La Cruz Ave',
    'La Prenda Ave',
    'Labrador Ln',
    'Landahl Ct',
    'Lansing Cir',
    'Larkin Ct',
    'Larkin Dr',
    'Larkspur Ct',
    'Laurel Ct',
    'Leeds Ct',
    'Lilac Ct',
    'Linda Vista St',
    'Lindo St',
    'Lloyd Ct',
    'London Cir',
    'London Dr',
    'Lori Dr',
    'Lupine Ct',
    'Lyon Ct',
    'Main Gate Terrace',
    'Mallard Dr',
    'Maple',
    'Marina Pl',
    'Marina Village Way',
    'Martin Ct',
    'Mary Ct',
    'Mayo Ct',
    'Mcallister Dr',
    'Mccall Dr',
    'Mckay Way',
    'Mckenna Ct',
    'Mckinney Pl',
    'Merlin Ct',
    'Military E',
    'Military W',
    'Mills Ct',
    'Mills Dr',
    'Mizner Ct',
    'Monroe Ct',
    'Mountain View Terrace',
    'Myrtle Ct',
    'Noyes Ct',
    'Oak',
    'Oak Rd',
    'Oakridge Ln',
    'Ofarrell Dr',
    'Ohare Dr',
    'Old Lake Herman Rd',
    'Old Suisun Rd',
    'Olive Branch Ct',
    'Orchid Ct',
    'Oxford Way',
    'Pacifica Ct',
    'Palm',
    'Panorama Ct',
    'Panorama Dr',
    'Park Rd',
    'Paul Ct',
    'Periwinkle Pl',
    'Perth Way',
    'Phelps Ct',
    'Pierce Ln',
    'Piercy Dr',
    'Plaza De Oro',
    'Pointe Benicia Way',
    'Polk St',
    'Poppy Cir',
    'Primrose Ln',
    'Radnor Ct',
    'Rankin Way',
    'Raymond Dr',
    'Redwood',
    'Reed Ct',
    'Regis Ct',
    'Reservoir Rd',
    'Ridge Cir',
    'Rinconada Ct',
    'Riverhill Dr',
    'Riverview Terrace',
    'Robinson Way',
    'Rose Dr',
    'Sage Ct',
    'Samuel Ct',
    'Sanborn Ct',
    'Sandy Way',
    'Sargent Ct',
    'Sea Breeze Dr',
    'Semple Crossing',
    'Semple Ct',
    'Shannon Ct',
    'Sherman Dr',
    'Shirley Dr',
    'Silas Ct',
    'Snapdragon Dr',
    'Solano Dr',
    'Southampton Rd',
    'Sprig Dr',
    'St Augustine Ct',
    'St Augustine Dr',
    'St Catherine Ln',
    'St Catherines Square',
    'St Francis Ct',
    'State Park Rd',
    'Stephen Ct',
    'Steven Cir',
    'Steven Ct',
    'Stone Rd',
    'Stoneman Ct',
    'Stuart Ct',
    'Sub Station Rd',
    'Sunrise Ct',
    'Sunset Cir',
    'Susan Ct',
    'Sweetbrier Ln',
    'Tamara Ct',
    'Teal Ct',
    'Teal Dr',
    'Thomas Dr',
    'Townsend Dr',
    'Toyon Pl',
    'Tulip Ct',
    'Turner Dr',
    'Tustin Ct',
    'Tyne Ct',
    'Union Ct',
    'Valerie Ct',
    'Vanns Landing',
    'Varni Ct',
    'Vecino St',
    'Via Alta',
    'Via Media',
    'Viewmont St',
    'Vincent Ct',
    'Violet Ct',
    'Vista Ct',
    'Vista Grande Ave',
    'W 10th St',
    'W 11th St',
    'W 12th St',
    'W 13th St',
    'W 14th St',
    'W 2nd St',
    'W 3rd St',
    'W 4th St',
    'W 5th St',
    'W 6th St',
    'W 7th St',
    'W 8th St',
    'W 9th St',
    'W Channel Rd',
    'W G St',
    'W I St',
    'W Industrial Way',
    'W J St',
    'W K St',
    'W L St',
    'W M St',
    'W N St',
    'W Seaview Dr',
    'W Tennys Dr',
    'Wainwright St',
    'Walnut',
    'Walsh Ct',
    'Wanger St',
    'Ware Ct',
    'Warwick Dr',
    'Water Way',
    'Watson Ct',
    'Weldon Ct',
    'White Chapel Dr',
    'Willow Ct',
    'Windsor Dr',
    'Wingfield Way',
    'Wisteria Ct',
    'Woodbridge Ct',
    'Woodgreen Way',
    'Woodstock Ct',
    'Wool Ct',
    'York Dr',
    'Zinnia Ct'
);