<?php
/**
 * Author: Hari Dornala <hari.dornala@nextbeemedia.com>
 * Date: 12-Apr-16
 * Time: 12:38 AM
 */

return array(
    'Acacia Steps',
    'Acacia Walk',
    'Acroft Ct',
    'Acton Cir',
    'Acton Crescent',
    'Acton St',
    'Ada St',
    'Addison St',
    'Ajax Pl',
    'Alamo Ave',
    'Allston Way',
    'Allston Way',
    'Altavista Path',
    'Alvarado Rd',
    'Amador Ave',
    'Amito Ave',
    'Amito Dr',
    'Anne Brower Path',
    'Anthony St',
    'Arcade Ave',
    'Arcade Ln',
    'Arch St',
    'Arden Path',
    'Arlington Ave',
    'Ashby Ave',
    'Ashby Pl',
    'Atlas Pl',
    'Avalon Ave',
    'Avalon Walk',
    'Avenida Dr',
    'Avis Rd',
    'Bancroft Steps',
    'Bancroft Way',
    'Barrow Ln',
    'Bataan Ave',
    'Bateman St',
    'Bay Tree Ln',
    'Bay View Pl',
    'Belrose Ave',
    'Benvenue Ave',
    'Berkeley Square',
    'Berkeley Way',
    'Berryman Path',
    'Berryman St',
    'Billie Jean Walk',
    'Blake St',
    'Boise St',
    'Bolivar Dr',
    'Bonar St',
    'Bonnie Ln',
    'Bowditch St',
    'Boynton Ave',
    'Boynton Walk',
    'Breakwater Dr',
    'Bret Harte Path',
    'Bret Harte Rd',
    'Bret Harte Way',
    'Bristol Dr',
    'Browning St',
    'Buena Ave',
    'Buena Ct',
    'Burnett St',
    'Byron St',
    'Camelia St',
    'Canyon Rd',
    'Capistrano Ave',
    'Carleton St',
    'Carlotta Ave',
    'Carrison St',
    'Catherine Dr',
    'Centennial Dr',
    'Center St - University Of Ca Berkeley',
    'Chancellor Pl',
    'Chaucer St',
    'Chester Ln',
    'Chilton Way',
    'Claremont Blvd',
    'Claremont Crescent',
    'Codornices Rd',
    'Colorado Ave',
    'Columbia Cir',
    'Colusa Ave',
    'Comstock Ct',
    'Contra Costa Ave',
    'Cowper St',
    'Cragmont Ave',
    'Creston Rd',
    'Crystal Way',
    'Curtis St',
    'Cutter Way',
    'Cyclotron Rd University Of California',
    'Dartmouth Dr',
    'Deakin St',
    'Del Norte St',
    'Derby St',
    'Devon Way',
    'Dohr St',
    'Domingo Ave',
    'Doris Pl',
    'Dowling Pl',
    'Drury Ln',
    'Drury Rd',
    'Dwight Crescent',
    'Dwight Pl',
    'Dwight Way',
    'Dwight Way',
    'E Parnassus Ct',
    'Easter Way',
    'Eastway Dr',
    'Edith St',
    'Edwards St',
    'El Camino Real',
    'El Dorado Ave',
    'El Mirador Path',
    'El Paseo Path',
    'El Portal Ct',
    'Ellis St',
    'Ellsworth St',
    'Elmwood Ct',
    'Encina Pl',
    'Encina Walk',
    'Ensenada Ave',
    'Eola St',
    'Eshleman Rd University Of California',
    'Etna St',
    'Eton Ave',
    'Eton Ct',
    'Eunice St',
    'Evergreen Ln',
    'Fairlawn Dr',
    'Fernwald Rd',
    'Fishing Pier',
    'Florida Ave',
    'Florida Walk',
    'Folger Ave',
    'Forest Ave',
    'Forest Ln',
    'Fountain Walk',
    'Fresno Ave',
    'Fulton St',
    'Garber St',
    'Gayley Rd University Of California',
    'Golf Course Dr',
    'Grant St',
    'Gravatt Dr',
    'Grayson St',
    'Greenwood Com',
    'Greenwood Terrace',
    'Gypsy Ln',
    'Halcyon Ct',
    'Halkin Ln',
    'Harding Cir',
    'Harmon St',
    'Harmon Way University Of California',
    'Harold Way',
    'Harvard Cir',
    'Haskell St',
    'Haste St',
    'Haviland Rd University Of California',
    'Hawthorne Terrace',
    'Hawthorne Terrace Steps W',
    'Hazel Rd',
    'Hearst Avenue University Of California',
    'Heinz Ave',
    'High Ct',
    'Highland Pl',
    'Hilgard Ave',
    'Hill Ct',
    'Hilldale Ave',
    'Hillview Rd',
    'Holmes Path',
    'Hopkins Ct',
    'Hopkins St',
    'Horseshoe (clark Kerr Main Driveway)',
    'Hospital Dr',
    'Indian Rock Ave',
    'Indian Rock Path',
    'Indian Trail',
    'Jaynes St',
    'Jefferson Ave',
    'Jones St',
    'Josephine St',
    'Juanita Way',
    'Julia St',
    'Keeler Ave',
    'Keith Ave',
    'Kelsey St',
    'Kenilworth Rd',
    'Kentucky Ave',
    'Keoncrest Dr',
    'Keoncrest Path',
    'Kittredge St',
    'La Loma Ave',
    'La Vereda Rd',
    'Latham Ln',
    'Latham Walk',
    'Laurel Ln',
    'Le Conte Ave',
    'Le Roy Ave',
    'Leroy Ave',
    'Lewiston Ave',
    'Lincoln St',
    'Linden Ave',
    'Lorina St',
    'Los Angeles Ave',
    'Lower Covert Path',
    'Mabel St',
    'Madera St',
    'Marin Ave',
    'Marlborough Terrace',
    'Martin Luther King Jr Way',
    'Martinez Path',
    'Maryland Ave',
    'Maryland Walk',
    'Mathews St',
    'Maybeck Twin Dr',
    'Mcgee Ave',
    'Mendocino Path',
    'Menlo Pl',
    'Michigan Ave',
    'Milvia St',
    'Miramonte Ct',
    'Modoc St',
    'Monterey Ave',
    'Montrose Rd',
    'Mosswood Ln',
    'Mosswood Rd',
    'Muir Way',
    'Murray St',
    'My Way',
    'N Valley St',
    'Napa Ave',
    'Nogales St',
    'Northampton Ave',
    'Northside Ave',
    'Oak Knoll Path',
    'Oak Knoll Terrace',
    'Oak Ridge Rd',
    'Oak Street Path',
    'Oakvale Ave',
    'Olympus Ave',
    'Orchard Ln',
    'Oregon St',
    'Otis St',
    'Overlook Rd',
    'Oxford Ln',
    'Oxford St',
    'Panoramic Way',
    'Pardee St',
    'Park Hills Rd',
    'Parker St',
    'Parnassus Path',
    'Parnassus Rd',
    'Perth Pl',
    'Piedmont Ave',
    'Piedmont Crescent',
    'Pine Ave',
    'Pine Path',
    'Pinnacle Path',
    'Plaza Dr',
    'Poe St',
    'Poplar Path',
    'Poppy Ln',
    'Poppy Path',
    'Prince St',
    'Regal Rd',
    'Ridge Rd',
    'Rispin Dr',
    'Roble Ct',
    'Rochdale Way',
    'Rock Ln',
    'Rock Walk',
    'Roosevelt Ave',
    'Rose St',
    'Rose Walk',
    'Rosemont Ave',
    'Roslyn Ct',
    'Rugby Ave',
    'Rugby Ave',
    'Russell St',
    'S Hall Rd University Of California',
    'San Benito Rd',
    'San Fernando Ave',
    'San Lorenzo Ave',
    'San Luis Rd',
    'San Mateo Rd',
    'San Ramon Ave',
    'Santa Barbara Rd',
    'Santa Barbara Rd',
    'Sather Rd',
    'Seawall Dr',
    'Senior Ave',
    'Shasta Rd',
    'Shasta Rd',
    'Shasta Rd',
    'Shattuck Pl',
    'Shattuck Square',
    'Sierra St',
    'Siler Pl',
    'Slater Ln',
    'Smyth Rd',
    'Sojourner Truth Ct',
    'Solano Ave Tunnel',
    'Somerset Pl',
    'Southampton Ave',
    'Southwest Pl University Of California',
    'Spaulding Ave',
    'Spinnaker Way',
    'Sport Ln University Of California',
    'Spring Way',
    'Stadium Rim Way',
    'Station Pl',
    'Stephens Way',
    'Stevenson Ave',
    'Stoddard Way',
    'Stonewall Rd',
    'Strathmoor Dr',
    'Summer St',
    'Summit Ln',
    'Summit Rd',
    'Sunset Ln',
    'Sutter St',
    'Tacoma Ave',
    'Tamalpais Path',
    'Tamalpais Rd',
    'Tanglewood Rd',
    'Terminal Pl',
    'Terrace Walk',
    'The Cir',
    'The Crescent',
    'The Crossways',
    'The Footway',
    'The Plaza Dr',
    'The Shortcut',
    'The South Crossways',
    'The Spiral',
    'The Steps',
    'The Uplands',
    'Tomlee Dr',
    'Tulare Ave',
    'Twain Ave',
    'Tyler St',
    'University Ave',
    'Upton Ln',
    'Vassar Ave',
    'Vermont Ave',
    'Vicente Pl',
    'Vicente Rd',
    'Vincente Ave',
    'Vincente Walk',
    'Vine Ln',
    'Vine St',
    'Virginia Gardens',
    'Virginia St Exd',
    'Visalia Ave',
    'Visalia Steps',
    'Vistamont Ave',
    'Vistamont Ct',
    'W Parnassus Ct',
    'Walker St',
    'Ward St',
    'Warring St',
    'West Cir University Of California',
    'Westmoorland Dr',
    'Westview Pl',
    'Wheeler St',
    'Whitaker Ave',
    'Wickson Rd University Of California',
    'Wildcat Canyon Rd',
    'Willard Pl',
    'Willow Walk',
    'Wilson Cir',
    'Woodhaven Rd',
    'Woodmont Ave',
    'Woodmont Ct',
    'Woodside Rd',
    'Woolsey St',
    'Yolo Ave',
    'Yosemite Rd',
    'Yosemite Steps'
);