<?php

return  array(
    'Adams Ct',
    'Adams Dr',
    'Alder Pl',
    'Alexis Ct',
    'Alice Ln',
    'Alma Ln',
    'Alma St',
    'Almanor Ave',
    'Alto Ln',
    'Altschul Ave',
    'Ambar Way',
    'American Way',
    'Anderson Way',
    'Arbol Grande Ct',
    'Arbor Rd',
    'Arlington Way',
    'Arnold Way',
    'Arrowhead Ln',
    'Athlone Ct',
    'Athlone Way',
    'Atkinson Ln',
    'August Cir',
    'Ayres Ln',
    'Ballard Ln',
    'Barney Ave',
    'Barney Ct',
    'Barron St',
    'Barton Way',
    'Bay Laurel Dr',
    'Bayfront Expy',
    'Bellair Way',
    'Bieber Ave',
    'Biltmore Ln',
    'Birkdale Ln',
    'Bishop Oak Ct',
    'Blackburn Ave',
    'Blake St',
    'Blueridge Ave',
    'Bohannon Dr',
    'Bolton Pl',
    'Brady Pl',
    'Brandon Way',
    'Branner Dr',
    'Brent Ct',
    'Burgess Dr',
    'Burnell Ln',
    'Byers Dr',
    'Callie Ln',
    'Cambridge Ave',
    'Campbell Ave',
    'Campbell Ln',
    'Campo Bello Ct',
    'Campo Bello Ln',
    'Carlton Ave',
    'Carriage Ct',
    'Carter Way',
    'Cascade Dr',
    'Castle Way',
    'Cathy Pl',
    'Cerros Manor',
    'Chapel Ln',
    'Cheryl Pl',
    'Chester St',
    'Chilco St',
    'Christopher Way',
    'Chrysler Dr',
    'Claire Pl',
    'Claremont Pl',
    'Claremont Way',
    'Clayton Dr',
    'Cleland Pl',
    'Cloud Ave',
    'Colby Ave',
    'Coleman Ave',
    'Coleman Pl',
    'Commonwealth Dr',
    'Concord Dr',
    'Continental Dr',
    'Corine Ln',
    'Corinne Ln',
    'Cornell Rd',
    'Cotton Pl',
    'Cotton St',
    'Crane St',
    'Crane Way',
    'Creek Dr',
    'Crest Ln',
    'Curtis St',
    'Curtis Way',
    'D St',
    'Deanna Dr',
    'Del Norte Ave',
    'Delfino Way',
    'Derry Ln',
    'Doris Dr',
    'Doyle St',
    'Dunne Ct',
    'Dunsmuir Way',
    'Durham St',
    'E Creek Dr',
    'E Creek Pl',
    'E Homewood Pl',
    'Eastridge Ave',
    'Edgewood Ln',
    'Elder Ct',
    'Elizabeth Ln',
    'Elliott Dr',
    'Elmwood Pl',
    'Emma Ln',
    'Evelyn St',
    'Falk Ct',
    'Fanita Way',
    'Felton Dr',
    'Felton Pl',
    'Florence Ln',
    'Franks Ln',
    'Fredrick Ct',
    'Fremont Pl',
    'French Ct',
    'Garland Dr',
    'Garland Pl',
    'Garwood Way',
    'Gilbert Ave',
    'Ginger St',
    'Gloria Cir',
    'Grace Dr',
    'Grayson Ct',
    'Greenwood Pl',
    'Haight St',
    'Hallmark Cir',
    'Hamilton Ct',
    'Hanna Way',
    'Happy Hollow Ln',
    'Harkins Ave',
    'Harmon Dr',
    'Harrison Way',
    'Harvard Ave',
    'Haven Ct',
    'Hazel St',
    'Hedge Rd',
    'Helen Pl',
    'Henderson Ave',
    'Henderson Pl',
    'Hermosa Pl',
    'Hermosa Way',
    'Hesketh Ct',
    'Hesketh Dr',
    'Hidden Oaks Dr',
    'Hill Ave',
    'Hillside Ave',
    'Hillview Pl',
    'Hobart St',
    'Hollyburne Ave',
    'Homewood Pl',
    'Hopkins St',
    'Hospital Pz',
    'Howard St',
    'Independence Dr',
    'Ivy Dr',
    'Jefferson Dr',
    'Johnston Ln',
    'Kelly Ct',
    'Kent Pl',
    'Kenwood Dr',
    'Klamath Dr',
    'La Loma Dr',
    'Lassen Ct',
    'Laurel Pl',
    'Lee Dr',
    'Leland Ave',
    'Lemon St',
    'Lennox Ave',
    'Lexington Dr',
    'Light Way',
    'Linfield Dr',
    'Linfield Pl',
    'Live Oak Ave',
    'Loma Prieta Ln',
    'Lomitas Ct',
    'Lorelei Ln',
    'Lorne Ct',
    'Lorne Ln',
    'Los Robles Ct',
    'Louise St',
    'Loyola Ave',
    'Lucky Ave',
    'Madera Ave',
    'Magnolia Ct',
    'Mallet Ct',
    'Maloney St',
    'Manor Pl',
    'Mansion Ct',
    'Marcussen Dr',
    'Market Pl',
    'Marmona Ct',
    'Marmona Dr',
    'May Brown Ave',
    'Maywood Ln',
    'Mckendry Dr',
    'Mckendry Pl',
    'Menlo Oaks Dr',
    'Merrill St',
    'Middle Ave',
    'Middle Ct',
    'Mielke Dr',
    'Millie Ave',
    'Mills Ct',
    'Mills St',
    'Modoc Ave',
    'Montana Ln',
    'Monte Rosa Dr',
    'Morandi Ln',
    'Morey Dr',
    'Morgan Ln',
    'N Lemon Ave',
    'Nancy Way',
    'Nash Ave',
    'Network Cir',
    'Noel Dr',
    'Nova Ln',
    'O Keefe St',
    'Oak Ave',
    'Oak Hollow Way',
    'Oak Knoll Ln',
    'Oak Ln',
    'Oakdell Dr',
    'Oakfield Ln',
    'Oakhurst Pl',
    'Oakland Ave',
    'Oakwood Pl',
    'Obrien Dr',
    'Okeefe St',
    'Olive St',
    'Oliver Ct',
    'Palm Ct',
    'Palmer Ln',
    'Palo Alto Way',
    'Partridge Ave',
    'Patricia Pl',
    'Patterson Ave',
    'Paulson Cir',
    'Peggy Ln',
    'Pembroke Pl',
    'Peninsula Way',
    'Pepperwood Ct',
    'Pierce Rd',
    'Pineview Ln',
    'Plumas Ave',
    'Politzer Dr',
    'Pope St',
    'Poppy Ave',
    'Randall Pl',
    'Ravenswood Ave',
    'Recreation Ave',
    'Redwood Ave',
    'Regal Ct',
    'Reyna Pl',
    'Riordan Pl',
    'Robert S Dr',
    'Robin Way',
    'Roble Ave',
    'Rondo Way',
    'Rosefield Way',
    'Rosemary St',
    'Royal Oak Ct',
    'Rural Ln',
    'Russell Ct',
    'Ryans Ln',
    'S Perimeter Rd',
    'Saga Ln',
    'San Andreas Ct',
    'San Clemente',
    'San Luis Dr',
    'San Mateo Dr',
    'Sand Hill Cir',
    'Sand Hill Rd At Sharon Park D',
    'Sandlewood St',
    'Santa Cruz Ave',
    'Santa Cruz Ave',
    'Santa Margarita Ave',
    'Santa Monica Ave',
    'Santa Rita Ave',
    'Saxon Way',
    'Schwie Al',
    'Scott Dr',
    'Seminary Dr',
    'Sevier Ave',
    'Seymour Ln',
    'Sharon Oaks Dr',
    'Sharon Park Dr',
    'Sharon Rd',
    'Sheridan Dr',
    'Sherwood Way',
    'Shirley Way',
    'Shoppe Ln',
    'Siskiyou Dr',
    'Siskiyou Pl',
    'Sneckner Ct',
    'Sonoma Ave',
    'Sonoma Pl',
    'Spiros Way',
    'St Francis Ct',
    'St Francis Pl',
    'Stanford Ct',
    'Sterling Ave',
    'Stone Pine Ln',
    'Stowe Ct',
    'Sunset Ct',
    'Sunset Ln',
    'Survey Ln',
    'Susan Gale Ct',
    'Sussex Pl',
    'Tehama Ave',
    'Terminal Ave',
    'Theresa Ct',
    'Thurlow St',
    'Tioga Dr',
    'Trinity Ct',
    'Trinity Dr',
    'Tudor Dr',
    'University Dr',
    'Vasilakos Ct',
    'Vasilakos Way',
    'Versailles St',
    'W 4th St',
    'Wallea Dr',
    'Warner Range Ave',
    'Waverley Ct',
    'Waverley St',
    'Wendy Way',
    'Werth Ave',
    'Westfield Dr',
    'Whitaker Way',
    'White Oak Ct',
    'White Oak Dr',
    'Whitney Ct',
    'Whitney Dr',
    'Wildwood Ln',
    'William Ct',
    'Willow Pl',
    'Windermere Ave',
    'Wood Ln',
    'Woodland Ct',
    'Yale Rd',
    'Zachary Ct'
);
