<?php

return  array(
    'Aberdeen Ln',
    'Ada Ave',
    'Adele Ave',
    'Aitken Ave',
    'Alamo Ct',
    'Aldean Ave',
    'Aleynna Pl',
    'Alice Ave',
    'Alison Ave',
    'Alley Way',
    'Alta Ave',
    'Alvin St',
    'Amalfi Way',
    'Amherst Way',
    'Amphitheatre Pkwy',
    'Ana Privada',
    'Andre Ave',
    'Andsbury Ave',
    'Anna Ave',
    'Annie Laurie Ave',
    'Annie Laurie St',
    'Anthony Ct',
    'Anza St',
    'Appletree Ln',
    'Apricot Ln',
    'Armand Ave',
    'Asbury Way',
    'Ashley Pl',
    'Astor Ct',
    'Avery Dr',
    'Awalt Dr',
    'Barbara Ave',
    'Bayshore Pkwy',
    'Beach Blvd',
    'Beacon St',
    'Beatrice St',
    'Beaume Ct',
    'Beaumont Square',
    'Bedford Dr',
    'Bedford Loop',
    'Begen Ave',
    'Bella Corte',
    'Bella Vista Ave',
    'Benjamin Dr',
    'Bentley Square',
    'Bernardo Ave',
    'Berry Ct',
    'Betlo Ave',
    'Beverly St',
    'Bill Graham Pkwy',
    'Blackfield Way',
    'Blue Lake Square',
    'Bond Way',
    'Bonita Way',
    'Bonny St',
    'Boranda Ave',
    'Borello Way',
    'Bourbon Ct',
    'Brenton Ct',
    'Brighton Pl',
    'Broderick Way',
    'Brook Pl',
    'Brookdale Ave',
    'Brower Ave',
    'Bruckner Cir',
    'Bryant Ave',
    'Bryant St',
    'Bryn Mawr Ct',
    'Burgoyne St',
    'Calderon Ave',
    'Cambridge Ln',
    'Cameron Dr',
    'Camille Ct',
    'Camp Ave',
    'Campbell Dr',
    'Canna Ct',
    'Cappelletti Ct',
    'Carla Ct',
    'Carlos Privada',
    'Carmelita Dr',
    'Carol Ave',
    'Carver Pl',
    'Casa Grande Ave',
    'Casey Ave',
    'Cassandra Way',
    'Castro St',
    'Cedarbrook Way',
    'Centre St',
    'Chagall St',
    'Charles Way',
    'Charleston Rd',
    'Charmain Cir',
    'Chatham Way',
    'Cherrytree Ln',
    'Chesley Ave',
    'Chesley Ct',
    'Chetwood Dr',
    'Chiquita Ave',
    'Christobal Privada',
    'Church St',
    'Churin Dr',
    'Coast Ave',
    'College St',
    'Collins Ct',
    'Colony St',
    'Columbia Dr',
    'Comstock Queen Ct',
    'Concord Cir',
    'Continental Cir',
    'Cornelia Ct',
    'Corto St',
    'Cottage Ct',
    'Crane Ave',
    'Creeden Way',
    'Creek Way',
    'Crisanto Ave',
    'Crittenden Ln',
    'Cuernavaca Circulo',
    'Cypress Point Dr',
    'Dale Ave',
    'Dali Ave',
    'Dalma Dr',
    'Davie Way',
    'De France Ave',
    'Deerwood Ct',
    'Del Medio Ave',
    'Del Medio Ct',
    'Dell Ave',
    'Dennis Ln',
    'Devonshire Ave',
    'Devonshire Ct',
    'Devoto St',
    'Devri Ct',
    'Diablo Ave',
    'Diericx Ct',
    'Diericx Dr',
    'Doane Ave',
    'Donovan Way',
    'Doverton Square',
    'Doyle Pl',
    'Drew Ave',
    'Drucilla Dr',
    'Durand Rd',
    'E Dana St',
    'E Middlefield Rd',
    'Easy St',
    'Ednamary Way',
    'Ehrhorn Ave',
    'Eichler Ct',
    'Eichler Dr',
    'El Centro',
    'El Ranchito Way',
    'Eldora Dr',
    'Elena Privada',
    'Ellis St',
    'Elmwood St',
    'Elsie Ave',
    'Emerson Ln',
    'Emily Dr',
    'Emmons Dr',
    'Empire Ct',
    'Ernestine Ln',
    'Escuela Ave',
    'Espinosa Ln',
    'Estrada Dr',
    'Eunice Ave',
    'Evandale Ave',
    'Excell Ct',
    'Fable Ct',
    'Fair Oaks Ave',
    'Fair Oaks St',
    'Fairbrook Dr',
    'Fairchild Dr',
    'Fairhaven Ct',
    'Fairmont Ave',
    'Farley St',
    'Farrel Ct',
    'Fay Way',
    'Fayette Dr',
    'Ferguson Dr',
    'Ferry Morse Way',
    'Filomena Ct',
    'Flores',
    'Flower Ln',
    'Flynn Ave',
    'Fordham Ct',
    'Fordham Way',
    'Forest Glen St',
    'Fountain Park Ln',
    'Foxborough Dr',
    'Frances Way',
    'Franklin Ave',
    'Franklin Ct',
    'Freedom Ln',
    'Front Ln',
    'Gabriel Ave',
    'Gala Ave',
    'Gamel Way',
    'Gantry Way',
    'Garcia Ave',
    'Garden Terrace',
    'Gemini Ave',
    'Georgetown Ct',
    'Georgetown Dr',
    'Gest Dr',
    'Gilmore St',
    'Gladys Ct',
    'Glen Alpine Ct',
    'Glen Una Ct',
    'Glenborough Dr',
    'Glenmead Ct',
    'Glenwood Ct',
    'Golf Ct',
    'Goli Ct',
    'Granada Dr',
    'Granada Park Cir',
    'Greenview Dr',
    'Gretel Ln',
    'Greyhawk Ct',
    'Hackett Ave',
    'Hamwood Terrace',
    'Hanford',
    'Hans Ave',
    'Harpster Dr',
    'Hart Ct',
    'Heartwood Ln',
    'Hedgerow Ct',
    'Helen Jean Way',
    'Hermosa',
    'Higdon Ave',
    'High School Way',
    'Hilary Ave',
    'Hillwood Ct',
    'Hilo Ct',
    'Hockney Ave',
    'Holland Ct',
    'Hopper Way',
    'Horizon Ave',
    'Hospital Dr',
    'Houghton St',
    'Hunsacker Rd',
    'Huntington Ct',
    'Independence Ave',
    'Irene Ct',
    'Iris Dr',
    'Isabelle Ave',
    'Isis Ct',
    'Ivan Way',
    'J T Jones Rd',
    'Jacaranda Dr',
    'Jackson Alley',
    'James Dr',
    'Jane Ln',
    'Jason Way',
    'Jean Ave',
    'Jeanie Lee Way',
    'Jenkins Ln',
    'Jennifer Ct',
    'Jessie Ln',
    'Jewell Pl',
    'Joaquin Rd',
    'Jordan Ct',
    'Judson Dr',
    'Kahlo St',
    'Karen Way',
    'Kasra Dr',
    'Kathy Jean Way',
    'Kathy Way',
    'Katie Ct',
    'Katrina Way',
    'Keller Dr',
    'Kentmere Ct',
    'Kenzo Ct',
    'Kern Ct',
    'Kimberly Way',
    'Kings Row',
    'Kittoe Dr',
    'Kittyhawk Way',
    'La Avenida St',
    'La Avenida St',
    'Lambert Ln',
    'Lambert Way',
    'Landings Dr',
    'Lane Ave',
    'Lassen Ave',
    'Latham St',
    'Lauella Ct',
    'Laura Ln',
    'Laurel Way',
    'Layla Ct',
    'Lee Dr',
    'Leksich Ave',
    'Lemontree Ct',
    'Leona Ln',
    'Leong Dr',
    'Leslie Ct',
    'Levin Ave',
    'Levin Ct',
    'Lida Dr',
    'Limetree Ln',
    'Lincoln Dr',
    'Linda Vista Ave',
    'Lloyd Way',
    'Logue Ave',
    'Lola Ln',
    'Lorene Ct',
    'Loreto St',
    'Lotus Ln',
    'Lubich Dr',
    'Luce Ct',
    'Lynwood Ave',
    'Magnolia Ave',
    'Magritte Way',
    'Marcelyn Ave',
    'Marcia Ct',
    'Mardell Way',
    'Margo Dr',
    'Maria Privada',
    'Marianne Ct',
    'Marilyn Ct',
    'Marilyn Dr',
    'Marilyn Pl',
    'Marine Way',
    'Mariner Dr',
    'Marjorie Ct',
    'Martens Ave',
    'Maryton Ave',
    'Mccarty Ave',
    'Medoc Ct',
    'Melba Ct',
    'Mercy St',
    'Middlefield Ave',
    'Midrock Cors',
    'Milano Way',
    'Milton Ct',
    'Minaret Ave',
    'Minton Ln',
    'Miro Ave',
    'Moffett Blvd',
    'Moffett Field Nas Boundary',
    'Mondrian Ave',
    'Montalto Dr',
    'Monte Vista',
    'Montebello Ave',
    'Montecito Ave',
    'Montelena Ct',
    'Monterey',
    'Moorpark Way',
    'Moorpark Way',
    'Moraga Dr',
    'Morgan Ct',
    'Morgan St',
    'Morning Sun Ct',
    'Morton Ct',
    'Mountain Laurel Ct',
    'Mountain Shadows Dr',
    'Mt Vernon Ct',
    'Muir Dr',
    'Murlagan Ave',
    'N Bernardo Ave',
    'N Rengstorff Ave',
    'N Shoreline Blvd',
    'N Whisman Rd',
    'Nedson Ct',
    'Newbury Dr',
    'Newman Pl',
    'Newton Dr',
    'Nilda Ave',
    'North Dr',
    'Okeefe Way',
    'Oak Haven Pl',
    'Oak Ln',
    'Oak Ln',
    'Oak St',
    'Oberg Ct',
    'Old Middlefield Way',
    'Olive Ct',
    'Orangetree Ln',
    'Orchard Glen Ct',
    'Ormonde Dr',
    'Ormonde Way',
    'Oro Way',
    'Ortega Ave',
    'Our Ln',
    'Owens Ct',
    'Pacchetti Way',
    'Palmer Ave',
    'Palmita Pl',
    'Palomas',
    'Pamela Dr',
    'Paragon Ct',
    'Park Dr',
    'Parker Ave',
    'Paseo Ct',
    'Pastel Ln',
    'Paul Ave',
    'Penny Ln',
    'Pepperwood Ct',
    'Perich Ct',
    'Permanente Way',
    'Petie Ct',
    'Petie Way',
    'Pettis Ave',
    'Phyllis Ct',
    'Piazza Dr',
    'Pioneer Way',
    'Plaza Ct',
    'Plum Ct',
    'Plumtree Ln',
    'Plymouth St',
    'Polaris Ave',
    'Polk Ct',
    'Poppy Pl',
    'Porterfield Ct',
    'Potter St',
    'Preston Ct',
    'Preston Dr',
    'Priscilla Ct',
    'Promethean Way',
    'Pumice St',
    'R T Jones Rd',
    'Ramos Ct',
    'Raspberry Ln',
    'Rathmore Ln',
    'Ravendale Dr',
    'Rebecca Privada',
    'Redcliff Ct',
    'Redwood Ct',
    'Reinert Ave',
    'Reinert Ct',
    'Reinert Rd',
    'Rengstorff Ave',
    'Rhone Ct',
    'Rialto Ct',
    'Rich Ave',
    'Rich Pl',
    'Richard Ct',
    'Rincon St',
    'Robin Terrace',
    'Rock Ct',
    'Rock St',
    'Ronden Ct',
    'Roslyn Cir',
    'Runningwood Cir',
    'Rustic Ln',
    'Ruth Ave',
    'S Rengstorff Ave',
    'S Shoreline Blvd',
    'S Whisman Rd',
    'Salado Dr',
    'San Ardo Way',
    'San Carlos Ave',
    'San Carrizo Way',
    'San Clemente Way',
    'San Domar Dr',
    'San Leandro Ave',
    'San Lucas Ave',
    'San Lucas Ct',
    'San Luis Ave',
    'San Luppe Dr',
    'San Pablo Dr',
    'San Pierre Way',
    'San Ramon Ct',
    'San Simeon Dr',
    'San Veron Ave',
    'Santa Clara Ave',
    'Santa Rosa Ave',
    'Satake Ct',
    'Saw Mill Ct',
    'Saw Mill Ln',
    'Serena Ct',
    'Sevely Dr',
    'Shady Spring Ln',
    'Shary Ave',
    'Shelby Dr',
    'Sherland Ave',
    'Sherland Cir',
    'Sherland Ct',
    'Shorebird Way',
    'Showers Dr',
    'Sierra Vista Ave',
    'Silverwood Ave',
    'Skyview Ct',
    'Sladky Ave',
    'Sleeper Ave',
    'Snow St',
    'Snyder Ln',
    'Solace Pl',
    'Solana Ct',
    'Solice Pl',
    'Sonia Way',
    'Springer Rd',
    'Springview Dr',
    'St Emilion Ct',
    'St Emilion Way',
    'St Giles Ln',
    'St Julien Ct',
    'St Julien Way',
    'Stacey Ct',
    'Stamm Ct',
    'Starr Way',
    'Stierlin Ct',
    'Stierlin Rd',
    'Stockwell Dr',
    'Sun Mor Ave',
    'Sunnyview Ln',
    'Sussex Square',
    'Sutter Creek Ln',
    'Suzette Ln',
    'Swanson Way',
    'Sylvan Ave',
    'Tahoe Terrace',
    'Tamalpais St',
    'Tami Way',
    'Tanfield Dr',
    'Taylor Ct',
    'Telford Ave',
    'Terminal Blvd',
    'Terri Lynn Way',
    'Thaddeus Dr',
    'The Americana',
    'Thomas Ct',
    'Thompson Ave',
    'Thompson Square',
    'Tiana Ln',
    'Todd St',
    'Toft St',
    'Town Square Dr',
    'Towne Cir',
    'Toyon St',
    'Tripiano Ct',
    'Trophy Dr',
    'Tryna Dr',
    'Tyler Park Way',
    'Tyrella Ave',
    'Tyrella Ct',
    'Valencia Ave',
    'Van Buren Cir',
    'Vaquero Dr',
    'Varsity Ct',
    'Vassar Ave',
    'Velarde St',
    'Vernon Cir',
    'Victor Way',
    'Victory Ave',
    'Vida Ct',
    'View St',
    'Villa',
    'Villa Nueva Ct',
    'Villa Nueva Way',
    'Villa Robleda Dr',
    'Villa St',
    'Village Ct',
    'W Dana St',
    'Wagner Ave',
    'Wake Forest Dr',
    'Walker Dr',
    'Walkway',
    'Waltham St',
    'Warner Ct',
    'Wasatch Dr',
    'Waverly Pl',
    'Welcome',
    'Wellesley Ct',
    'Wentworth St',
    'Wescoat Ct',
    'Westford Way',
    'Whelan Ct',
    'Whisman Ct',
    'Whisman Park Dr',
    'Whisman Station Dr',
    'Whitney Ct',
    'Whitney Dr',
    'Whits Rd',
    'Wicker Dr',
    'Wild Cherry Ln',
    'Wildflower Park Ln',
    'Wildrose Way',
    'Wiley Terrace',
    'Williams Way',
    'Willowgate St',
    'Windingwood Ct',
    'Windmill Park Ln',
    'Windrose Pl',
    'Winfield Dr',
    'Winston Pl',
    'Winwood Ct',
    'Woburn Ct',
    'Woodberry Ln',
    'Woodgreen Ln',
    'Woodgreen Way',
    'Woodhaven Pl',
    'Woodland Park Ln',
    'Woodleaf Way',
    'Wortham Ct',
    'Wyandotte St',
    'Wyeth St',
    'Yardis Ct',
    'Yorkshire Way',
    'Yorkton Dr',
    'Yuba Dr'
);