<?php
/**
 * Author: Hari Dornala <hari.dornala@nextbeemedia.com>
 * Date: 30-Mar-16
 * Time: 1:49 AM
 */

return  array(
    "Abbey Ct",
    "Abbotford Ct",
    "Abington Ct",
    "Abington Dr",
    "Addition Rd",
    "Ajuga Ct",
    "Albyn Ct",
    "Aleppo Dr",
    "Alpenrose Ct",
    "Alpine St",
    "Amador Pl",
    "Amaryllis Pl",
    "Anjou Pl",
    "Anvers Pl",
    "Aralia Dr",
    "Arbeau Dr",
    "Arden St",
    "Argonne Pl",
    "Arrowhead Pl",
    "Ash St",
    "Ashbourne Ct",
    "Aster Ct",
    "Baine Ave",
    "Bath Pl",
    "Bayonne Dr",
    "Bayonne Pl",
    "Beech Pl",
    "Bellflower Dr",
    "Bellhaven Ave",
    "Bellhaven Pl",
    "Benecia Ave",
    "Bennington Dr",
    "Bettencourt St",
    "Beutke Dr",
    "Biddle Ave",
    "Birch Pl",
    "Birch St",
    "Birkdale Dr",
    "Birkshire Pl",
    "Biscay Pl",
    "Bishop Way",
    "Bitterroot Ave",
    "Blackburn Dr",
    "Blackwood Dr",
    "Bluegrass Ct",
    "Bolton Pl",
    "Bonnie St",
    "Bottle Brush Ct",
    "Braidburn Ave",
    "Brandywine St",
    "Breton Dr",
    "Breton Pl",
    "Bridgepointe Dr",
    "Bristol Pl",
    "Brittany Ave",
    "Broadway Ave",
    "Broadway Pl",
    "Buckeye Pl",
    "Buckeye St",
    "Buckingham Ct",
    "Burdick St",
    "Burning Tree Dr",
    "Byington Dr",
    "Cabernet Ave",
    "Cabot Ct",
    "Calais Pl",
    "Camass Ct",
    "Campanula Ct",
    "Cardiff St",
    "Carleen Ct",
    "Carter Ave",
    "Casey Ct",
    "Castillon Dr",
    "Castleford Ct",
    "Cedar Ct",
    "Channel Dr",
    "Chapman Dr",
    "Charles St",
    "Charmwood Ct",
    "Cheviot Ct",
    "Christine St",
    "Cinnabar Ct",
    "Civic Terrace Ave",
    "Clark Ave",
    "Cleremont Dr",
    "Cluny Pl",
    "Colbert Pl",
    "Colbert St",
    "Columbine Pl",
    "Conestoga Pl",
    "Cornwall Pl",
    "Cotton Ave",
    "Crocus Ct",
    "Croydon Pl",
    "Crystal Springs Ct",
    "Crystal Springs Dr",
    "Curie Pl",
    "Cypress Point Dr",
    "Dairy Ave",
    "Dalewood Ct",
    "Dalewood Dr",
    "Daphne Ct",
    "Darvon Ct",
    "Darvon St",
    "Deborah St",
    "Del Monte Ave",
    "Delphinium Ct",
    "Derby Pl",
    "Dichondra Pl",
    "Dijon Dr",
    "Donegal Ct",
    "Dorchester Ct",
    "Dorking Ct",
    "Dugan Ct",
    "Dumas Pl",
    "Dumbarton Ct",
    "Dupont Ave",
    "Ebbetts St",
    "Enfield Dr",
    "Enterprise Ct",
    "Enterprise Dr",
    "Ervin Ct",
    "Escallonia Ct",
    "Escallonia Dr",
    "Eureka Dr",
    "Exeter Ct",
    "Ezra Dr",
    "Fair Ct",
    "Falmouth Pl",
    "Farnham Dr",
    "Fir Ct",
    "Fircrest St",
    "Firestone Ct",
    "Flanders Dr",
    "Flanders Pl",
    "Flintwood Dr",
    "Forbes Dr",
    "Fountaine Ave",
    "Fowler St",
    "Fuschia Ct",
    "Galletta Dr",
    "Garrone Ave",
    "Garrone Pl",
    "George Ave",
    "Geranium Ct",
    "Geranium St",
    "Goldenrod Dr",
    "Graham Ave",
    "Greenpoint Ct",
    "Greenpoint St",
    "Greenwich Ct",
    "Guava Dr",
    "Guava Pl",
    "Gum Ct",
    "Hafner Ct",
    "Hafner St",
    "Hafner Way",
    "Haley St",
    "Harlon Ct",
    "Hazelnut Dr",
    "Hazelnut Pl",
    "Hebrides Ct",
    "Hermitage Ave",
    "Hill St",
    "Honeysuckle Ct",
    "Honeysuckle Dr",
    "Humber Pl",
    "Hyacinth St",
    "Idlewild Ct",
    "Indian Wells Ct",
    "Indian Wells Dr",
    "Ingraham St",
    "Inverness Dr",
    "Ipswich Ct",
    "Iris Ct",
    "Jacaranda Ct",
    "Jarvis Ave",
    "Jasmine Ave",
    "Jennifer St",
    "Joaquin Murieta Ave",
    "John Muir Dr",
    "Jonathan Dr",
    "Jonathan Pl",
    "Jonquil Dr",
    "Juniper Ave",
    "Kiote Dr",
    "La Salle Dr",
    "Lake Blvd",
    "Lakewood Ct",
    "Lakewood Dr",
    "Landes Pl",
    "Larkspur St",
    "Lavender Pl",
    "Leone St",
    "Levi St",
    "Lido Blvd",
    "Lido Ct",
    "Linden Ct",
    "Lobelia Dr",
    "Long St",
    "Lotus Ct",
    "Lundy Dr",
    "Madelaine Dr",
    "Madelaine Pl",
    "Mahogany Pl",
    "Maidstone Ct",
    "Manzanita St",
    "Maple St",
    "Marguerite Dr",
    "Market Ave",
    "Marne Pl",
    "Marsten Dr",
    "Martel Pl",
    "Mayhews Landing Rd",
    "Mcdonald Ave",
    "Mclaughlin Ave",
    "Meadowlark Ct",
    "Merion Dr",
    "Milani Ave",
    "Millwood Ct",
    "Mirabeau Dr",
    "Mistflower Ave",
    "Mockorange Ct",
    "Montcalm Ave",
    "Moores Ave",
    "Morning Glory Ct",
    "Morton Ave",
    "Mowry School Rd",
    "Munyan St",
    "Musick Ave",
    "N Magazine",
    "Narcissus Ave",
    "Nelson Pl",
    "Newark Blvd",
    "Newcastle Ct",
    "Newpark Mall",
    "Noel Ave",
    "Normandy Dr",
    "Northampton Ct",
    "Norwich Pl",
    "Nutmeg Ct",
    "Oldham Pl",
    "Oleander Dr",
    "Olympic Ct",
    "Orkney Ct",
    "Orleans Dr",
    "Overlake Pl",
    "Oxford Pl",
    "Papaya St",
    "Par Ct",
    "Parada St",
    "Parkshore Dr",
    "Parkside Pl",
    "Peach Ct",
    "Peachtree Ave",
    "Pebble Beach Ave",
    "Peppertree Ct",
    "Persimmon Pl",
    "Peugeot Pl",
    "Picardy Pl",
    "Plummer Ave",
    "Pomegranate Ave",
    "Port Anchorwood Pl",
    "Port Fogwood Pl",
    "Port Sailwood Dr",
    "Port Tidewood St",
    "Potrero Dr",
    "Preston Pl",
    "Provance St",
    "Quartz Pl",
    "Quicksilver Ave",
    "Quince Pl",
    "Radcliffe Ave",
    "Ramsgate Dr",
    "Ravenwood Ave",
    "Reina Pl",
    "Reymouth Dr",
    "Rich Ave",
    "Rinconada Ct",
    "Robertson Ave",
    "Rochelle Ave",
    "Rockport Ct",
    "Rockrose Ct",
    "Rockrose Dr",
    "Rockspray St",
    "Rubicon Ave",
    "Rugby Pl",
    "Ruschin Dr",
    "S Magazine",
    "Salisbury Dr",
    "Sandalwood St",
    "Scarborough Dr",
    "Severn Dr",
    "Severn Pl",
    "Shady Hollow Dr",
    "Shelley Ct",
    "Sheridan Ct",
    "Shorehaven Ave",
    "Shorehaven Pl",
    "Silk Ct",
    "Silverado Pl",
    "Smith Ave",
    "Snow Ave",
    "Souza Ave",
    "Spruce Ct",
    "St Christopher St",
    "St Christopher Way",
    "St Edwards St",
    "St Isabel Ave",
    "St Luke Ct",
    "St Mark Ave",
    "St Matthew Dr",
    "St Paul Dr",
    "Stafford Pl",
    "Starflower Ct",
    "Starflower St",
    "Station Rd",
    "Stirling Ct",
    "Stonecress Ave",
    "Sugar Pine Ct",
    "Sunrose Ave",
    "Surrey Ct",
    "Sussex Pl",
    "Swindon Pl",
    "Sycamore St",
    "Tait Ct",
    "Tanforan Ct",
    "Tenaya Ave",
    "Timber St",
    "Tottenham Ct",
    "Toulon Pl",
    "Toulouse St",
    "Tourraine Dr",
    "Tourraine Pl",
    "Tozier St",
    "Truckee Ct",
    "Tudor Pl",
    "Tunbridge Dr",
    "Tyne Pl",
    "Vinewood St",
    "Wells Ave",
    "Wembley Ct",
    "Wentworth Pl",
    "Willow Pl",
    "Wilma Ave",
    "Windemere Dr",
    "Windermere Dr",
    "Wingate Pl",
    "Winsford Ct",
    "Wintergreen Dr",
    "Woodbine Pl",
    "Woodruff Dr",
    "Worthing Dr",
    "Wycombe Pl",
    "Yarmouth Ct",
    "Zulmida Ave"
);