<?php
/**
 * Author: Hari Dornala <hari.dornala@nextbeemedia.com>
 * Date: 30-Mar-16
 * Time: 1:52 AM
 */

return array(
    '2nd St',
    'Abel Ave',
    'Addison Ave',
    'Adobe Pl',
    'Agnes Way',
    'Alannah Ct',
    'Alder Ln',
    'Alester Ave',
    'Alexis Dr',
    'Alger Dr',
    'Alma St',
    'Almanor Ln',
    'Alta Mesa Ave',
    'Altaire Walk',
    'Amaranta Ave',
    'Amaranta Ct',
    'Amarillo Ave',
    'Ames Ave',
    'Ames Ct',
    'Amherst St',
    'Anton Ct',
    'Arastradero Rd',
    'Arbol Dr',
    'Arcadia Pl',
    'Arrowhead Way',
    'Arroyo Ct',
    'Ashby Dr',
    'Ashton Ave',
    'Avalon Ct',
    'Aztec Way',
    'Baker Ave',
    'Bandera Dr',
    'Barron Ave',
    'Bautista Ct',
    'Baylor St',
    'Bellview Dr',
    'Ben Lomond Dr',
    'Bibbits Dr',
    'Birch St',
    'Blair Ct',
    'Blake Wilbur Dr',
    'Boyce Ave',
    'Bret Harte St',
    'Briarwood Way',
    'Bruce Dr',
    'Bryant Ct',
    'Bryson Ave',
    'Burnham Way',
    'Byron St',
    'Calcaterra Pl',
    'Campana Dr',
    'Campesino Ave',
    'Cardinal Way',
    'Carlitos Ct',
    'Carlson Cir',
    'Carlson Ct',
    'Carolina Ln',
    'Cass Way',
    'Castilleja Ave',
    'Cedar St',
    'Celia Dr',
    'Center Dr',
    'Cereza Dr',
    'Cesano Ct',
    'Chabot Terrace',
    'Charles Marx Way',
    'Charleston Ct',
    'Chaucer St',
    'Cherry Oaks Pl',
    'Chimalus Dr',
    'Christine Dr',
    'Churchill Ave',
    'Clara Dr',
    'Clemo Ave',
    'Clifton Ct',
    'Coastland Dr',
    'Coleridge Ave',
    'Colorado Ave',
    'Colorado Pl',
    'Columbia St',
    'Community Ln',
    'Corina Way',
    'Cork Oak Way',
    'Cornell St',
    'Corporation Way',
    'Coulombe Dr',
    'Country Club Ct',
    'Cowper Ct',
    'Cowper St',
    'Coyote Hill Rd',
    'Crosby Pl',
    'Curlew Ln',
    'Dake Ave',
    'Darlington Ct',
    'Dartmouth St',
    'Davenport Way',
    'Dennis Dr',
    'Deodar St',
    'Diablo Ct',
    'Dinah s Ct',
    'Dixon Pl',
    'Donald Dr',
    'Donner Ln',
    'Downing Ln',
    'Driftwood Dr',
    'Driscoll Ct',
    'Driscoll Pl',
    'Duluth Cir',
    'Duncan Pl',
    'Durand Way',
    'Dymond Ct',
    'E Crescent Dr',
    'E Greenwich Pl',
    'E Meadow Cir',
    'E Meadow Dr',
    'Edgewood Dr',
    'Edlee Ave',
    'Egret Ln',
    'El Cajon Way',
    'El Camino Way',
    'El Carmelo Ave',
    'El Centro St',
    'El Verano Ave',
    'Elbridge Way',
    'Ellsworth Pl',
    'Elmdale Pl',
    'Elsinore Ct',
    'Elsinore Dr',
    'Elwell Ct',
    'Ely Pl',
    'Embarcadero Bike Path',
    'Embarcadero Rd',
    'Embarcadero Way',
    'Emerson St',
    'Encina Ave',
    'Encina Grande Dr',
    'Erstwild Ct',
    'Escobita Ave',
    'Everett Ave',
    'Everett Ct',
    'Evergreen Dr',
    'Faber Pl',
    'Fabian St',
    'Fabian Way',
    'Fairmede Ave',
    'Fallen Leaf St',
    'Feather Ln',
    'Fernando Ave',
    'Ferne Ave',
    'Ferne Ct',
    'Fielding Ct',
    'Fielding Dr',
    'Fife Ave',
    'Florales Dr',
    'Flowers Ln',
    'Frandon Ct',
    'Fulton St',
    'Gailen Ave',
    'Gailen Ct',
    'Garland Dr',
    'Gary Ct',
    'Gaspar Ct',
    'Genevieve Ct',
    'Geng Rd',
    'George Hood Ln',
    'Gilman St',
    'Glenbrook Dr',
    'Goebel Ave',
    'Grant Ave',
    'Green Manor',
    'Greenwood Ave',
    'Greer Rd',
    'Grove Ave',
    'Grove Ct',
    'Grove Ln',
    'Guinda St',
    'Gunn High School Bike Path',
    'Hale St',
    'Hanover St',
    'Hansen Way',
    'Harker Ave',
    'Harriet St',
    'Harvard St',
    'Heather Ln',
    'Heron Way',
    'Higgins Pl',
    'Hilbar Ln',
    'Homer Ave',
    'Hopkins Ave',
    'Hubbartt Dr',
    'Hutchinson Ave',
    'Ilima Ct',
    'Ilima Way',
    'Indian Dr',
    'Industrial Ave',
    'Interdale Way',
    'Iris Way',
    'Irven Ct',
    'Island Dr',
    'Jacaranda Ln',
    'Jackson Dr',
    'Jacobs Ct',
    'James Rd',
    'Janice Way',
    'Jefferson Dr',
    'Jordan Pl',
    'Josina Ave',
    'Juniper Ln',
    'Juniper Way',
    'Kellogg Ave',
    'Kelly Way',
    'Kendall Ave',
    'Kenneth Dr',
    'Kent Pl',
    'King Arthur Ct',
    'Kings Ln',
    'Kingsley Ave',
    'Kipling St',
    'Kirby Pl',
    'Klamath Ln',
    'La Calle Ct',
    'La Donna Ave',
    'La Jennifer Way',
    'La Mata Way',
    'La Para Ave',
    'La Selva Dr',
    'Laguna Ave',
    'Laguna Oaks Pl',
    'Laguna Way',
    'Lake Ave',
    'Lambert Ave',
    'Lane 59 E',
    'Laurel Glen Dr',
    'Layne Ct',
    'Lindero Dr',
    'Ln 13 E',
    'Ln 15 E',
    'Ln 20',
    'Ln 30 E',
    'Ln 33',
    'Ln 39',
    'Ln 56',
    'Ln 7 E',
    'Ln 7 W',
    'Ln 8 W',
    'Ln A W',
    'Ln B E',
    'Ln B W',
    'Ln D E',
    'Ln D W',
    'Lois Ln',
    'Loma Verde Ave',
    'Loma Verde Pl',
    'Lorabelle Ct',
    'Lorabelle Ln',
    'Los Palos Ave',
    'Los Palos Cir',
    'Los Palos Pl',
    'Los Robles Ave',
    'Los Trancos Rd',
    'Louis Rd',
    'Louisa Ct',
    'Lowell Ave',
    'Lumas Verdes Ave',
    'Lupine Ave',
    'Lytton Ave',
    'Mackall Way',
    'Mackay Dr',
    'Maclane St',
    'Maddux Dr',
    'Madeline Ct',
    'Madison Way',
    'Madrono Ave',
    'Mallard Ln',
    'Manchester Ct',
    'Manuela Ave',
    'Manuela Ct',
    'Manuela Way',
    'Manzana Ln',
    'Maplewood Pl',
    'Margarita Ave',
    'Marion Ave',
    'Marion Pl',
    'Mariposa Ave',
    'Marira Pl',
    'Mark Twain St',
    'Marlowe St',
    'Marshall Dr',
    'Martinsen Ct',
    'Matadero Ave',
    'Matadero Ct',
    'Maureen Ave',
    'May Ct',
    'Maybell Ave',
    'Maybell Way',
    'Mayview Ave',
    'Mckellar Ln',
    'Melville Ave',
    'Mesa Ave',
    'Mesa Ct',
    'Metro Cir',
    'Middlefield Rd',
    'Midtown Ct',
    'Military Way',
    'Miranda Ave',
    'Miranda Green St',
    'Mitchell Ln',
    'Moana Ct',
    'Moffett Cir',
    'Montrose Ave',
    'Moraga Ct',
    'Moreno Ave',
    'Morris Dr',
    'Morton St',
    'Mosher Way',
    'Mumford Pl',
    'Murdoch Ct',
    'Murdoch Dr',
    'Murray Way',
    'N California Ave',
    'N Tolman Dr',
    'Nathan Ct',
    'Nathan Way',
    'New Mayfield Ln',
    'Newberry Ct',
    'Newell Pl',
    'Newell Rd',
    'Newell Rd',
    'Noble St',
    'O Brine Ln',
    'Oak Creek Dr',
    'Oak Hill Ave',
    'Oberlin St',
    'Old Trace Ct',
    'Old Trace Rd',
    'Oregon Ave',
    'Oregon Expy',
    'Orinda St',
    'Orme St',
    'Ortega Ct',
    'Otterson Ct',
    'Oxford Ave',
    'Palo Alto Square',
    'Paloma Dr',
    'Paradise Ct',
    'Paradise Way',
    'Park Blvd',
    'Parkinson Ave',
    'Parkside Dr',
    'Pasteur Dr',
    'Patricia Ln',
    'Pear Ln',
    'Pena Ct',
    'Phillips Rd',
    'Piers Ct',
    'Pine St',
    'Pitman Ave',
    'Plover Ln',
    'Plum Ln',
    'Poe St',
    'Pomona Ave',
    'Ponce Dr',
    'Portage Ave',
    'Portal Pl',
    'Porter Dr',
    'Price Ct',
    'Princeton St',
    'Rambow Dr',
    'Ramona Cir',
    'Ramona St',
    'Randers Ct',
    'Redwood Cir',
    'Regent Pl',
    'Rhodes Dr',
    'Richardson Ct',
    'Rickeys Ln',
    'Rickeys Way',
    'Rinconada Ave',
    'Robb Rd',
    'Roble Ridge Rd',
    'Rorke Way',
    'Rosewood Dr',
    'Ross Ct',
    'Ross Rd',
    'Ruthelma Ave',
    'Ruthven Ave',
    'S California Ave',
    'S Tolman Dr',
    'San Carlos Ct',
    'San Jude Ave',
    'San Jude St',
    'Sandpiper Ln',
    'Sandra Pl',
    'Santa Catalina St',
    'Santa Rita Ave',
    'Scripps Ave',
    'Scripps Ct',
    'Seale Ave',
    'Seminole Way',
    'Seneca St',
    'Sevyson Ct',
    'Shauna Ln',
    'Sheridan Ave',
    'Sherman Ave',
    'Silva Ct',
    'Simkins Ct',
    'Somerset Pl',
    'South Ct',
    'Southampton Dr',
    'Spruce Ln',
    'St Francis Dr',
    'St Francis Terrace',
    'St Michael Ct',
    'St Michael Dr',
    'Stanford Shopping Center',
    'Stanislaus Ln',
    'Stanley Way',
    'Starr King Cir',
    'Staunton Ct',
    'Stelling Ct',
    'Stelling Dr',
    'Stockton Pl',
    'Stone Ln',
    'Sutherland Dr',
    'Suzanne Dr',
    'Swain Way',
    'Sweet Olive Way',
    'Tahoe Ln',
    'Talisman Ct',
    'Tanland Dr',
    'Tasso St',
    'Tennessee Ln',
    'Tennyson Ave',
    'Terman Dr',
    'Tevis Pl',
    'Thain Way',
    'The Cir',
    'Thomas Dr',
    'Timlott Ct',
    'Timlott Ln',
    'Tippawingo Ave',
    'Tippawingo St',
    'Torreya Ct',
    'Towle Pl',
    'Towle Way',
    'Toyon Pl',
    'Transport St',
    'Trinity Ln',
    'Tulip Ln',
    'Tuolumne Ln',
    'Urban Ln',
    'Van Auken Cir',
    'Ventura',
    'Ventura Ave',
    'Ventura Ct',
    'Verdosa Dr',
    'Vernon Terrace',
    'Victoria Pl',
    'Villa Real',
    'Villa Vera',
    'Villa Vista',
    'Vineyard Ln',
    'Vista Ave',
    'W Bayshore Rd',
    'W Charleston Rd',
    'W Crescent Dr',
    'W Greenwich Pl',
    'W Meadow Dr',
    'Wallis Ct',
    'Walter Hays Dr',
    'Warren Way',
    'Washington Ave',
    'Waverley Oaks',
    'Waverley St',
    'Webster St',
    'Welch Rd',
    'Wellesley St',
    'Wells Ave',
    'Wellsbury Ct',
    'Wellsbury Way',
    'Whitclem Ct',
    'Whitclem Dr',
    'Whitclem Pl',
    'Whitclem Way',
    'Whitman Ct',
    'Whitsell Ave',
    'Wildwood Ln',
    'Wilkie Ct',
    'Wilkie Way',
    'Williams St',
    'Willmar Dr',
    'Wilson St',
    'Wilton Ave',
    'Wintergreen Way',
    'Wisteria Ln',
    'Yale St',
    'Ynigo Way'
);