<?php
/**
 * Author: Hari Dornala <hari.dornala@nextbeemedia.com>
 * Date: 30-Mar-16
 * Time: 1:48 AM
 */

return array(
    "10th Ave",
    "11th Ave",
    "12th Ave",
    "13th Ave",
    "14th Ave",
    "15th Ave",
    "16th Ave",
    "17th Ave",
    "18th Ave",
    "19th Ave",
    "1st Ave",
    "21st Ave",
    "22nd Ave",
    "23rd Ave",
    "24th Ave",
    "26th Ave",
    "26th Pl",
    "27th Ave",
    "28th Ave",
    "29th Ave",
    "2nd Ave",
    "30th Ave",
    "31st Ave",
    "36th Ave",
    "37th Ave",
    "42nd Ave",
    "43rd Ave",
    "44th Ave",
    "6th Ave",
    "7th Ave",
    "8th Ave",
    "9th Ave",
    "Aberdeen Dr",
    "Ada St",
    "Adams St",
    "Adrian Ave",
    "Afton Ct",
    "Airport Blvd",
    "Alameda",
    "Alameda De Las Pulgas",
    "Alameda Delas Pulgas",
    "Alanhill Ln",
    "Alder Ln",
    "Alderwood Ct",
    "Alhambra Rd",
    "Allegheny Way",
    "Allison Ct",
    "Almaden Way",
    "Alpine Rd",
    "Alta Ave",
    "Amboy Ct",
    "Amesbury Ave",
    "Amherst Ave",
    "Amy Dr",
    "Anchor Rd",
    "Anna St",
    "Annapolis Dr",
    "Ansel Ln",
    "Antioch Dr",
    "Aquarius Ln",
    "Aragon Blvd",
    "Arbor Ln",
    "Archer Ct",
    "Ark St",
    "Arlington Ln",
    "Armada Way",
    "Arrowood Ln",
    "Arroyo Ct",
    "Aruba Ln",
    "Ascension Dr",
    "Ashwood Ct",
    "Ashwood Dr",
    "Avila Rd",
    "Avocet Ct",
    "Bahia St",
    "Baker Way",
    "Baldwin Ave",
    "Balmoral Ct",
    "Barkentine St",
    "Barneson Ave",
    "Barroilhet Ave",
    "Barton St",
    "Bay Landing",
    "Bayridge Way",
    "Bayshore Fwy",
    "Bayswater Ave",
    "Baytree Way",
    "Bayview Ave",
    "Baywood Ave",
    "Beacon Ave",
    "Bear Gulch Rd",
    "Belford Way",
    "Belmont Ave",
    "Ben Franklin Ct",
    "Bennington Ct",
    "Bennington Dr",
    "Beresford Ave",
    "Beresford Ct",
    "Beresford St",
    "Berkeley Ave",
    "Bermuda Dr",
    "Bettina Ave",
    "Betty Ln",
    "Beverly St",
    "Big Tree Way",
    "Birch Ave",
    "Bishop Ln",
    "Blakewood Way",
    "Blossom Cir",
    "Borden St",
    "Borel Ave",
    "Borel Pl",
    "Boston Ave",
    "Bovet Rd",
    "Bradley Ave",
    "Bradley Ct",
    "Brandywine Rd",
    "Branson Dr",
    "Bret Harte Way",
    "Briar Ln",
    "Bridgepointe Cir",
    "Bridgepointe Pkwy",
    "Broadview Ct",
    "Bromfield Rd",
    "Brooks St",
    "Bucknell Dr",
    "Budd Ct",
    "Buena Vista Ave",
    "Burbank Ave",
    "Burgoyne Ct",
    "Byrd Ln",
    "Byron Ave",
    "Cam A Los Cerros",
    "Camden Ave",
    "Campus Dr",
    "Canada Rd",
    "Canyon Oak Ct",
    "Capistrano Way",
    "Carey School Ln",
    "Caribbean Way",
    "Carlisle Dr",
    "Carmel Cir",
    "Cary Ave",
    "Casa De Campo",
    "Casa De Campo Way",
    "Casanova Dr",
    "Cascade Ct",
    "Casey Ct",
    "Castilian Way",
    "Catalpa St",
    "Cavanaugh St",
    "Caxton Ct",
    "Cedarwood Dr",
    "Celeste Dr",
    "Cerrito Ave",
    "Charing Cross Rd",
    "Charles Ln",
    "Charthouse Ln",
    "Cherrywood Dr",
    "Cheryl Ct",
    "Chesham Ave",
    "Chess Dr",
    "Chester Way",
    "Chesterton Pl",
    "Chestnut Ln",
    "Chris Ln",
    "Chukker Ct",
    "Church Ave",
    "Church Rd",
    "Clark Dr",
    "Claudia Ave",
    "Clearview Dr",
    "Clearview Way",
    "Cleveland Ave",
    "Clipper St",
    "Cobb St",
    "Cobblehill Pl",
    "Colegrove Ct",
    "Colegrove St",
    "Colgate Way",
    "College Ave",
    "Columbia Dr",
    "Compass Ln",
    "Concar Dr",
    "Condon Ct",
    "Connie Ave",
    "Coquito Way",
    "Cornell Ave",
    "Corte De Flores",
    "Cortez Ave",
    "Costa Rica Ave",
    "Cottage Grove Ave",
    "Countryside Dr",
    "Coyote Point Dr",
    "Cragmont Ct",
    "Crazy Petes Rd",
    "Creekridge Ct",
    "Creekside Ln",
    "Crescent Ave",
    "Crestview Dr",
    "Crestwood Ct",
    "Crestwood Dr",
    "Crio Ave",
    "Crippleridge Ct",
    "Crown Ct",
    "Crystal Springs Rd",
    "Csm Dr",
    "Cuesta Ave",
    "Culver Ct",
    "Cupertino Way",
    "Curtiss St",
    "Cypress Ave",
    "Daisy St",
    "Dakota Ave",
    "Dale Ave",
    "Dalehurst Ave",
    "Dalehurst Ct",
    "Darcy Ave",
    "Darcy Ct",
    "Darlene Ave",
    "Dartmouth Rd",
    "Darwin Ave",
    "David Ct",
    "David St",
    "Day Ave",
    "De Anza Blvd",
    "De Anza Ct",
    "De Sabla Rd",
    "Deer Lake Ct",
    "Del Monte Pl",
    "Del Monte St",
    "Del Ray St",
    "Del Rosa Way",
    "Delmar Way",
    "Denali Dr",
    "Detroit Dr",
    "Devonshire Blvd",
    "Dewey St",
    "Dix St",
    "Dolan Ave",
    "Dolores Ct",
    "Dolores St",
    "Dolphin Isle",
    "Donner St",
    "Dorchester Rd",
    "Dore Ave",
    "Douglas Ct",
    "Dublin Way",
    "Duggan Ct",
    "Duggan Rd",
    "Dumont St",
    "Durand Dr",
    "E 16th Ave",
    "E 20th Ave",
    "E 21st Ave",
    "E 25th Ave",
    "E 38th Ave",
    "E 39th Ave",
    "E 3rd Ave",
    "E 40th Ave",
    "E 41st Pl",
    "E 4th Ave",
    "E 5th Ave",
    "E Bellevue Ave",
    "E Capistrano Way",
    "E Ellsworth Ct",
    "E Grant Pl",
    "E Hillsdale Blvd",
    "E Hillsdale Ct",
    "E Laurel Creek Dr",
    "E Laurel Creek Rd",
    "E Laurie Meadow Dr",
    "E Lincoln Ave",
    "E Poplar Ave",
    "E Santa Inez Ave",
    "Eastwood Dr",
    "Eaton Rd",
    "Echo Ave",
    "Edgewater Blvd",
    "Edgewood Rd",
    "Edinburgh St",
    "Edison St",
    "Edna Way",
    "Eisenhower St",
    "El Camino Real",
    "El Cerrito Ave",
    "El Parque Ct",
    "El Portal Ave",
    "El Sobrante St",
    "Eleanor Dr",
    "Elk Tree Rd",
    "Elkhorn Ct",
    "Elliott St",
    "Elm St",
    "Emerald Bay Ln",
    "Emerald Ct",
    "Engle Rd",
    "Ensenada Way",
    "Erica Way",
    "Ericson Rd",
    "Estrella Way",
    "Eva Ct",
    "Evergreen St",
    "Fairfax Ave",
    "Fairfield Ct",
    "Fairmont Dr",
    "Fairoaks Ct",
    "Falda Ave",
    "Fallon Ave",
    "Fashion Island Blvd",
    "Fathom Dr",
    "Fernwood St",
    "Field House Rd - College Of San Mateo",
    "Fiesta Ave",
    "Fiesta Ct",
    "Fiesta Dr",
    "Fillmore Ave",
    "Fleetwood Dr",
    "Flint Ave",
    "Flores St",
    "Folkstone Ave",
    "Foothill Dr",
    "Fordham Rd",
    "Forge Rd",
    "Foster St",
    "Franklin Pkwy",
    "Franklin St",
    "French Creek Pl",
    "Fulton Rd",
    "Gabarda Way",
    "Gallowridge Ct",
    "Garden Ln",
    "Garfield St",
    "Garvey Way",
    "Gateway Dr",
    "George Ave",
    "Georgetown Ave",
    "Gillis Dr",
    "Ginnever St",
    "Glendale Rd",
    "Glendora Dr",
    "Gloria Ct",
    "Goldenridge Ct",
    "Gramercy Dr",
    "Grand Blvd",
    "Greenfield Ave",
    "Greenfield Ct",
    "Greenoak Ct",
    "Greenwood Ave",
    "Guildford Ave",
    "Gum St",
    "Gymkhana Rd",
    "Hacienda St",
    "Haddon Dr",
    "Halsey Ave",
    "Halyard Ln",
    "Hamlet St",
    "Hancock Ave",
    "Hanrahan Ct",
    "Harbor Blvd",
    "Harbor Seal Ct",
    "Harding Ave",
    "Harrison Ave",
    "Harrow Ave",
    "Harvard Rd",
    "Haskins Dr",
    "Hassler Rd",
    "Haven Ave",
    "Havenridge Ct",
    "Hawthorne Dr",
    "Hayne Rd - Golden Gate National Recreation Area",
    "Hayward Ave",
    "Heather Ln",
    "Helene Ct",
    "Helm Ln",
    "Hemlock Ave",
    "Herschel St",
    "Hickory Ln",
    "Highland Ave",
    "Highview Ct",
    "Highview Dr",
    "Hillbarn Ct",
    "Hillcrest Rd",
    "Hillsborough Blvd",
    "Hillsdale Pl",
    "Hillside Ct",
    "Hilltop Rd",
    "Himmel Ave",
    "Hobart Ave",
    "Holland St",
    "Homer Ln",
    "Homewood Ave",
    "Hoods Point Way",
    "Hosmer St",
    "Howard Ave",
    "Howe St",
    "Huddart Park Rd",
    "Hull Ave",
    "Humboldt Rd",
    "Humboldt St",
    "Hurlingham Ave",
    "Huron Ave",
    "Huron Ct",
    "Hwy 101",
    "Hwy 114",
    "Hwy 35",
    "Hwy 84",
    "Hwy 92",
    "Idyllwild Ave",
    "Indian Ave",
    "Industrial Rd",
    "Interstate 280",
    "Iowa Dr",
    "Iris Ct",
    "Irving St",
    "Isabelle Ave",
    "Ivy St",
    "J Hart Clinton Dr",
    "J. Arthur Younger Fwy",
    "Jackson St",
    "James Ct",
    "Jasmine St",
    "Jefferson Ct",
    "Joanne Dr",
    "Jody Ct",
    "Juniper St",
    "Junipero Serra Fwy",
    "Kalmia St",
    "Karen Rd",
    "Kathryne Ave",
    "Kehoe Ave",
    "Kelly St",
    "Kelton Ct",
    "Kent Ct",
    "Kent St",
    "Kentucky Ave",
    "Kenwood Ave",
    "Keswick Ln",
    "Kettering Ct",
    "Kimberly Way",
    "King Ct",
    "King Ln",
    "Kingridge Dr",
    "Kings Ln",
    "Kings Mountain Rd",
    "Klamath Ave",
    "Knapp Ct",
    "Kristin Ct",
    "La Casa Ave",
    "La Cuesta Dr",
    "La Honda Rd",
    "La Jolla Ave",
    "La Mesa Ct",
    "La Mesa Dr",
    "La Salle Dr",
    "La Selva Cir",
    "La Selva St",
    "Lafayette St",
    "Lago St",
    "Lake St",
    "Lakeshore Dr",
    "Lakewood Cir",
    "Landfair Ave",
    "Lansdale St",
    "Las Sombras Ct",
    "Laughing Cow Rd",
    "Laurel Ave",
    "Laurel Ct",
    "Laurel Hill Ct",
    "Laurel Hill Dr",
    "Laurelwood Dr",
    "Laurie Meadows Dr",
    "Lawrence Rd",
    "Leafwood Ct",
    "Leona St",
    "Leslie St",
    "Lessingia Ct",
    "Lexington Ave",
    "Linda Ct",
    "Lindbergh St",
    "Linden Ln",
    "Live Oak Dr",
    "Llano St",
    "Locust St",
    "Lodato Ave",
    "Lodi Ave",
    "Lola St",
    "Loma Rd",
    "Londonderry Dr",
    "Lorraine Ave",
    "Los Altos Dr",
    "Los Altos Pl",
    "Los Gatos Way",
    "Los Prados St",
    "Louise Ln",
    "Lula Belle Ln",
    "Lundys Ln",
    "Lyonridge Ln",
    "Macarthur Ave",
    "Madera Dr",
    "Madison Ave",
    "Madison Way",
    "Madrone Ct",
    "Magnolia Ave",
    "Magnolia Dr",
    "Maiden Ln",
    "Main St",
    "Maple St",
    "Margaret Ct",
    "Marina Blvd",
    "Marina Ct",
    "Marina Vista",
    "Mariners Island Blvd",
    "Marisma St",
    "Marshall Ave",
    "Martin Dr",
    "Mary Lu Ln",
    "Mason Ln",
    "Maxine Ave",
    "Mcaker Ct",
    "Mclellan Ave",
    "Meadow Ct",
    "Meadow View Pl",
    "Mefferd Ave",
    "Melissa Ct",
    "Melrose Ct",
    "Michael Dr",
    "Midvale Ave",
    "Midway Ave",
    "Milton St",
    "Mimosa Way",
    "Mira Way",
    "Mission Dr",
    "Monroe Ave",
    "Monte Diablo Ave",
    "Monterey St",
    "Monticello Rd",
    "Mounds Rd",
    "Mountain View Pl",
    "Mulberry Dr",
    "Mulryan Ct",
    "Murphy Ct",
    "Murphy Dr",
    "Murphy Pl",
    "Murray Ct",
    "N Amphlett Blvd",
    "N B St",
    "N Bayshore Blvd",
    "N Claremont St",
    "N Delaware St",
    "N El Camino Real",
    "N Eldorado St",
    "N Ellsworth Ave",
    "N Fremont St",
    "N Grant St",
    "N Humboldt St",
    "N Idaho St",
    "N Kingston St",
    "N Norfolk St",
    "N Quebec St",
    "N Railroad Ave",
    "N Rochester St",
    "N San Mateo Dr",
    "Nadina St",
    "Nash Dr",
    "Needleridge Ct",
    "Neptune Ct",
    "Nevada Ave",
    "New Brunswick Dr",
    "Newbridge Ave",
    "Newlands Ave",
    "Newport St",
    "Noe Ave",
    "Norton St",
    "Notre Dame Ave",
    "O'farrell St",
    "Oak St",
    "Oak Valley Rd",
    "Oakhill Ct",
    "Oakwood Dr",
    "Occidental Ave",
    "Ocean View Ave",
    "Old County Rd",
    "Olive Ct",
    "Olympic Ave",
    "Oneill Dr",
    "Ontario St",
    "Oregon Ave",
    "Orinda Dr",
    "Oriskany Dr",
    "Oso St",
    "Otay Ave",
    "Ottawa St",
    "Overland Dr",
    "Overlook St",
    "Oxford Ave",
    "Pacific Blvd",
    "Palm Ave",
    "Palm Pl",
    "Palomar Dr",
    "Palos Verdes Ct",
    "Palos Verdes Dr",
    "Park Ln",
    "Park Pl",
    "Parkside Way",
    "Parkview Way",
    "Parkwood Dr",
    "Parrott Ct",
    "Parrott Dr",
    "Pasadena Dr",
    "Patricia Ave",
    "Paulson Ct",
    "Pebblewood Way",
    "Peck Ave",
    "Pecora Way",
    "Peninsula Ave",
    "Perimeter Rd",
    "Pershing Ave",
    "Piccadilly Ln",
    "Pico Ave",
    "Pierce St",
    "Piers Ln",
    "Pike Ln",
    "Pilgrim Dr",
    "Pinecrest Terrace",
    "Pinewood Ct",
    "Pioneer Ct",
    "Playa St",
    "Poinsettia Ave",
    "Polhemus Rd",
    "Polk Ave",
    "Polo Ct",
    "Poppy Ct",
    "Port Dr",
    "Portola Dr",
    "Portsmouth Way",
    "Potomac Way",
    "Powell St",
    "Powhatan Pl",
    "Prague St",
    "Princeton Rd",
    "Prospect Row",
    "Prowshead Ln",
    "Queens Ave",
    "Queens Ln",
    "Quince St",
    "Rainbow Dr",
    "Ramblewood Way",
    "Ramona St",
    "Rand St",
    "Randall Rd",
    "Ranelagh Rd",
    "Reef Dr",
    "Regan Dr",
    "Rex St",
    "Rhus St",
    "Ridgecrest Terrace",
    "Roberta Dr",
    "Rock Harbor Ln",
    "Rockwood Ct",
    "Rogell Ave",
    "Rogell Ct",
    "Rolling Hills Ave",
    "Rosewood Dr",
    "Rosilie St",
    "Rossi Way",
    "Roxbury Ln",
    "Royal Ave",
    "Rte 35",
    "Rte 84",
    "Rte 92",
    "Rutherford Ave",
    "Ryder St",
    "S Amphlett Blvd",
    "S B St",
    "S Bayshore Blvd",
    "S Claremont St",
    "S Delaware St",
    "S El Camino Real",
    "S Eldorado St",
    "S Ellsworth Ave",
    "S Fremont St",
    "S Grant St",
    "S Humboldt St",
    "S Idaho St",
    "S Kingston St",
    "S Norfolk St",
    "S Palomar Dr",
    "S Quebec St",
    "S Railroad Ave",
    "S Rochester St",
    "S San Mateo Dr",
    "Salisbury Way",
    "San Antonio Ave",
    "San Benito St",
    "San Juan Ct",
    "San Miguel Ave",
    "San Miguel Way",
    "Sand Hill Rd",
    "Santa Clara Ave",
    "Santa Clara Way",
    "Santiago Ave",
    "Santiago St",
    "Saratoga Dr",
    "Scenic Way",
    "Scott St",
    "Sea Spray Ln",
    "Seabury Rd",
    "Seal St",
    "Seneca Ln",
    "Sequoia Ave",
    "Serra Ct",
    "Seville Way",
    "Sextant Ct",
    "Shafter St",
    "Sharon Pl",
    "Shasta Dr",
    "Shelbourne Pl",
    "Sheraton Pl",
    "Shoal Dr",
    "Shooting Star Isle",
    "Shoreline Dr",
    "Shoreview Ave",
    "Sky Ct",
    "Skyline Dr",
    "Skylonda Dr",
    "Sleepy Hollow Ln",
    "Sonora Dr",
    "South Blvd",
    "Southampton Way",
    "Southridge Ct",
    "Southwood Ave",
    "Spar Dr",
    "Speers Ave",
    "Springfield Way",
    "Spuraway Dr",
    "Spyglass Dr",
    "St Johns Ct",
    "St Marys Ct",
    "St Matthews Ave",
    "St Vincent Ln",
    "Stag Ave",
    "Stanford Ave",
    "Starboard Dr",
    "Starlite Dr",
    "State Route 114",
    "State Route 82",
    "State St",
    "Staysail Ct",
    "Stephen Rd",
    "Stern Ln",
    "Stoney Pl",
    "Stoney Point Pl",
    "Stowe Ln",
    "Stratford Way",
    "Studio Cir",
    "Sugarloaf Dr",
    "Sullivan St",
    "Sunnybrae Blvd",
    "Sunset Terrace",
    "Surfbird Isle",
    "Susan Ct",
    "Suzie St",
    "Sycamore Ave",
    "Sylvan Ave",
    "Tanglewood Way",
    "Tarrytown St",
    "Taylor St",
    "Tender Ln",
    "Tenderfoot Trail",
    "Terminal Pl",
    "Terrace Way",
    "Texas Way",
    "Thomas Ct",
    "Ticonderoga Dr",
    "Tilia St",
    "Tilton Ave",
    "Tilton Terrace",
    "Timberhead Ln",
    "Timberlane Rd",
    "Timberlane Way",
    "Tollridge Ct",
    "Tower Rd",
    "Toyon Ct",
    "Trader Ln",
    "Treetop Ln",
    "Trenton Pl",
    "Trinity St",
    "Trollman Ave",
    "Tulane Ct",
    "Tulane Rd",
    "Turner Terrace",
    "Turtle Bay Pl",
    "Vailwood Pl",
    "Vailwood Way",
    "Valley View Ct",
    "Van Buren St",
    "Vanessa Dr",
    "Ventura Ave",
    "Verano Ct",
    "Verdun Ave",
    "Vernon Terrace",
    "Via Laguna",
    "Viewridge Dr",
    "Villa Terrace",
    "Vine Ct",
    "Virginia Ave",
    "Vista Ave",
    "Vista Cay",
    "Vista Del Mar",
    "Vista Del Sol",
    "Voelker Dr",
    "W 20th Ave",
    "W 25th Ave",
    "W 38th Ave",
    "W 39th Ave",
    "W 3rd Ave",
    "W 40th Ave",
    "W 41st Ave",
    "W 4th Ave",
    "W 5th Ave",
    "W Bellevue Ave",
    "W Capistrano Way",
    "W Ellsworth Ct",
    "W Floresta Way",
    "W Grant Pl",
    "W Hillsdale Blvd",
    "W Laurie Meadow Dr",
    "W Point Pl",
    "W Poplar Ave",
    "W Santa Inez Ave",
    "W Selby Ln",
    "Warren Rd",
    "Washington St",
    "Waters Park Dr",
    "Wayne Way",
    "Weepingridge Ct",
    "Wellesley Ave",
    "Westmoreland Ave",
    "Westwood Ct",
    "Wharfside Rd",
    "White Plains Ct",
    "Whitecliff Ct",
    "Whitecliff Way",
    "Wildwood Dr",
    "Williams Pl",
    "Wilmington Rd",
    "Wilshire Ave",
    "Winward Way",
    "Winway Cir",
    "Wisnom Ave",
    "Wolfe Dr",
    "Woodberry Ave",
    "Woodbridge Cir",
    "Woodcreek Ct",
    "Woodland Dr",
    "Woodside Way",
    "Wooster Ave",
    "Wyoming Way",
    "Yale Dr",
    "Yates Way",
    "Yew St",
    "York Ave",
    "Yorktown Rd",
    "Young St"
);