<h1>Create Merchant</h1>
<div class="row table">
    <?php if ($this->message) { ?>
    <div class="alert <?php echo $this->message->class ?>"><?php echo $this->message->message ?></div>
    <?php } ?>
</div>
<div class="row table">
    <form method="POST">
        <div class="col-xs-12">
            <div class="col-xs-6">
                <input type="text" name="yelp_id" class="form-control" />
            </div>
            <div class="col-xs-3">
                <input type="submit" class="btn btn-success" value="Create Merchant" />
            </div>
        </div>
    </form>
</div>
