

<div class="container" style="margin-top: 55px;">
    <h2>Merchant List</h2>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Gender</th>
        </tr>
        </thead>

        <?php foreach ($this->customers as $customer) { ?>
            <tr>
                <td><?php echo $customer['first_name'] ?></td>
                <td><?php echo $customer['last_name'] ?></td>
                <td><?php echo $customer['email'] ?></td>
                <td><?php echo $customer['gender'] ?></td>
            </tr>

        <?php } ?>

    </table>

    <?php echo $this->paginator ?>

</div>

