

<div class="container" style="margin-top: 45px;">
    <div id="yodlee-yelp-mapper-section">

        <div  class="row heading" >
            <h2>Merchant - Bank Description Mapper</h2>
        </div>

        <form id="search-form">

        <input type="hidden" name="global_merchant_id" id="global_merchant_id" value="" />
        <input type="hidden" name="description" id="description" value="" />
        <input type="hidden" name="bank_id" id="bank_id" value="" />
        <input type="hidden" name="category_name" id="category_name" value="" />
        <div class="row table">
            <div class="col-xs-4">
                <select id="bank-select" class="form-control">
                    <option value="">Select Bank</option>
                    <?php foreach ($this->banks as $bank) { ?>
                        <option value="<?php echo $bank['bank_id'] ?>"><?php echo $bank['bank_name'] . ' (' . $bank['count'] . ')' ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-xs-4">
                <select id="category-select" class="form-control">
                    <option value="">Select Category</option>
                </select>
            </div>
            <div class="col-xs-4">
                <select id="description-select" class="form-control">
                    <option value="">Select Description</option>
                </select>
            </div>
<!--            <div class="col-xs-2">-->
<!--                <button id="btnRemoveTransaction" type="button" class="btn btn-block btn-danger">Remove</button>-->
<!--            </div>-->
        </div>        

        <div id="status-change" style="display: none;">
            <div class="row table">
                <div class="col-xs-12">
                    <input value="" type="text" name="description" id="description" readonly="readonly" class="form-control">
                </div>
            </div>
            <div class="row table">
                <div class="col-xs-4">
                    <select id="mappingStatus" name="mappingStatus" class="form-control">
                        <option value="">Select Status</option>
                        <option value="NeedHelp">Need Help</option>
                        <option value="2Locations">2 Locations</option>
                        <option value="MoreThan2Locations">More Than 2 Locations</option>
                        <option value="OutOfUSA">Out Of USA</option>
                        <option value="OnlineWebsite">Online Website</option>
                        <option value="CashWithdraw">Cash Withdraw</option>
                        <option value="Closed">Closed</option>
                        <option value="NoCityData">No City Data</option>
                        <option value="NotOnYelp">Not On Yelp</option>
                        <option value="DifferentAddress/City">Different Address/City</option>
                        <option value="NotFound">Not Found</option>
                        <option value="NotInAdminPanel">Not In Admin Panel</option>
                    </select>                    
                </div>
                <div class="col-xs-6">
                    <textarea name="mappingNotes" id="mappingNotes" class="form-control" rows="3" placeholder="Notes"></textarea>
                </div>
                <div class="col-xs-2">
                    <button id="submit-status" type="button" class="btn btn-block btn-danger">Submit</button>
                    <button id="submit-status-multiple" type="button" class="btn btn-block btn-warning" style="display: none;">Submit Multiple</button>
                </div>
            </div>
            <div id="multiple-selections-wrap" style="display: none;" class="row">
                <div class="col-md-12">
                    <h4>Select Multiple Locations</h4>
                    <select id="description-select-multiple" class="form-control" multiple="true"></select>
                </div>
            </div>
        </div>


        <div id="description-display" class="row table"></div>

        <div class="row table">
            <div class="col-md-4">
                <input name="mapping_part1" id="mapping_part1" class="form-control" type="text" placeholder="Mapping Part1">
            </div>
            <div class="col-md-4">
                <input name="mapping_part2" id="mapping_part2" class="form-control" type="text" placeholder="Mapping Part2">
            </div>
            <div class="col-md-4">
                <input name="mapping_part3" id="mapping_part3" class="form-control" type="text" placeholder="Mapping Part3">
            </div>
        </div>

        <div class="row table">
            <div class="col-xs-4">
                <input name="term" id="term" class="form-control" type="text" placeholder="Search Term">
            </div>
            <div class="col-xs-4">
                <input name="location" id="location" class="form-control" type="text" placeholder="Address">
            </div>
            <div class="col-xs-2">
                <button id="search-yelp" type="button" class="btn btn-block btn-primary">Search</button>
            </div>
            <div class="col-xs-2">
                <button id="add-online-merchant" type="button" class="btn btn-block btn-success">Add Merchant</button>
            </div>
        </div>

        </form>

        <div id="div-merchant-form">
        </div>

        <div id="results">
        </div>
    </div>


    <div id="google-place-section" style="display:none;">
        <h2>Merchant GooglePlace Map</h2>
        <form id="google-place-form">

            <div class="row table">
                <div class="col-xs-12">
                    <select id="global_merchant_select" name="global_merchant_id" class="form-control">
                        <option value="">Loading...</option>
                    </select>
                </div>
            </div>

            <div id="global-merchant-display" class="row col-md-12">
            </div>

            <div class="row table">
                <div class="col-xs-4">
                    <input name="gb-term" id="gb-term" class="form-control" type="text" placeholder="Search Term">
                </div>
                <div class="col-xs-5">
                    <input name="gb-location" id="gb-location" class="form-control" type="text" placeholder="Address">
                </div>
                <div class="col-xs-3">
                    <button id="search-google-place" type="button" class="btn btn-block btn-success disabled">Search Google Place</button>
                </div>
            </div>

        </form>

        <div id="google-place-results" class="row">

        </div>
    </div>



</div>


