<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                <tr>
                    <td>Bulk Upload Merchant Descriptions</td>
                    <td><button id="btn-blk-upload" class="btn btn-block btn-success">Run Script</button></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript" language="JavaScript">
$(function() {
    $('#btn-blk-upload').click(function() {
        $(this).html('Running...');
        $.get('/admin/index/runBulkUpload');
        $(this).html('Run Script');
    });
});
</script>